import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

// Managed Agents session ledger — issue #100 Step 1.
//
// Persists supervisor + sub-session metadata so any flow that fans out work
// across `client.beta.sessions.*` (Q1 ingest, Q2 scout, Q3 placement, Q5
// publish) can be replayed and audited. Shape mirrors `agentSession` in
// `convex/schema.ts`.
//
// Uses the *Generic builders because `convex/_generated` is not committed —
// it is regenerated by `npx convex dev` at provisioning time.

const STATUS_VALIDATOR = v.union(
  v.literal('running'),
  v.literal('paused'),
  v.literal('done'),
  v.literal('failed')
);

type AgentSessionStatus = 'running' | 'paused' | 'done' | 'failed';

interface AgentSessionDoc {
  _id: unknown;
  workspaceId: string;
  sessionId: string;
  parentSessionId?: string;
  purpose: string;
  status: AgentSessionStatus;
  createdAt: number;
  updatedAt: number;
}

function toRecord(doc: AgentSessionDoc) {
  return {
    id: String(doc._id),
    workspaceId: doc.workspaceId,
    sessionId: doc.sessionId,
    parentSessionId: doc.parentSessionId,
    purpose: doc.purpose,
    status: doc.status,
    createdAt: doc.createdAt,
    updatedAt: doc.updatedAt,
  };
}

export const insert = mutationGeneric({
  args: {
    workspaceId: v.string(),
    sessionId: v.string(),
    parentSessionId: v.optional(v.string()),
    purpose: v.string(),
    status: STATUS_VALIDATOR,
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const id = await ctx.db.insert('agentSession', {
      workspaceId: args.workspaceId,
      sessionId: args.sessionId,
      parentSessionId: args.parentSessionId,
      purpose: args.purpose,
      status: args.status,
      createdAt: now,
      updatedAt: now,
    });
    return String(id);
  },
});

export const setStatus = mutationGeneric({
  args: {
    sessionId: v.string(),
    status: STATUS_VALIDATOR,
  },
  handler: async (ctx, args) => {
    const doc = (await ctx.db
      .query('agentSession')
      .withIndex('by_session', (q: any) => q.eq('sessionId', args.sessionId))
      .unique()) as AgentSessionDoc | null;
    if (!doc) return null;
    await ctx.db.patch(doc._id as any, {
      status: args.status,
      updatedAt: Date.now(),
    });
    return String(doc._id);
  },
});

export const listByWorkspace = queryGeneric({
  args: { workspaceId: v.string() },
  handler: async (ctx, args) => {
    const docs = (await ctx.db
      .query('agentSession')
      .withIndex('by_workspace', (q: any) => q.eq('workspaceId', args.workspaceId))
      .order('asc')
      .take(500)) as AgentSessionDoc[];
    return docs.map(toRecord);
  },
});

export const getBySessionId = queryGeneric({
  args: { sessionId: v.string() },
  handler: async (ctx, args) => {
    const doc = (await ctx.db
      .query('agentSession')
      .withIndex('by_session', (q: any) => q.eq('sessionId', args.sessionId))
      .unique()) as AgentSessionDoc | null;
    return doc ? toRecord(doc) : null;
  },
});

export const listChildren = queryGeneric({
  args: { workspaceId: v.string(), parentSessionId: v.string() },
  handler: async (ctx, args) => {
    const docs = (await ctx.db
      .query('agentSession')
      .withIndex('by_workspace', (q: any) => q.eq('workspaceId', args.workspaceId))
      .order('asc')
      .take(500)) as AgentSessionDoc[];
    return docs
      .filter((d) => d.parentSessionId === args.parentSessionId)
      .map(toRecord);
  },
});
