import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

// Workspace brandPolicy persistence. Mirrors `ImageComposition` in
// lib/providers/image/types.ts — Convex stores the per-workspace default,
// and the image-gen request path composes it with any per-call override via
// `resolveComposition`. No UI yet; this is the data seam only.
//
// Uses the *Generic builders because convex/_generated isn't committed — it's
// regenerated by `npx convex dev` at provisioning time. The loss in type
// precision is acceptable for this CRUD surface.

const TEXT_STRATEGY_VALIDATOR = v.union(
  v.literal('none'),
  v.literal('baked'),
  v.literal('auto')
);

const COMPOSITION_VALIDATOR = v.object({
  textStrategy: v.optional(TEXT_STRATEGY_VALIDATOR),
  // Token union stays open at the storage layer so new tokens don't require
  // a schema migration; validation against the closed union lives in
  // `lib/providers/image/types.ts` + adapter mappers.
  constraints: v.optional(v.array(v.string())),
});

interface BrandPolicyDoc {
  _id: unknown;
  wsId: unknown;
  defaultComposition: {
    textStrategy?: 'none' | 'baked' | 'auto';
    constraints?: string[];
  };
  updatedAt: number;
}

function toRecord(doc: BrandPolicyDoc) {
  return {
    id: String(doc._id),
    wsId: String(doc.wsId),
    defaultComposition: doc.defaultComposition,
    updatedAt: doc.updatedAt,
  };
}

export const getBrandPolicy = queryGeneric({
  args: { wsId: v.id('workspace') },
  handler: async (ctx, args) => {
    const doc = (await ctx.db
      .query('brandPolicy')
      .withIndex('by_wsId', (q: any) => q.eq('wsId', args.wsId))
      .unique()) as BrandPolicyDoc | null;
    return doc ? toRecord(doc) : null;
  },
});

export const setDefaultComposition = mutationGeneric({
  args: {
    wsId: v.id('workspace'),
    composition: COMPOSITION_VALIDATOR,
  },
  handler: async (ctx, args) => {
    const existing = (await ctx.db
      .query('brandPolicy')
      .withIndex('by_wsId', (q: any) => q.eq('wsId', args.wsId))
      .unique()) as BrandPolicyDoc | null;
    const now = Date.now();
    if (existing) {
      await ctx.db.patch(existing._id as any, {
        defaultComposition: args.composition,
        updatedAt: now,
      });
      return String(existing._id);
    }
    const id = await ctx.db.insert('brandPolicy', {
      wsId: args.wsId,
      defaultComposition: args.composition,
      updatedAt: now,
    });
    return String(id);
  },
});
