import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

// Inbound-reply persistence for the X webhook receiver.
// Uses *Generic builders because convex/_generated is not committed;
// it is regenerated by `npx convex dev` at provisioning time.

export const recordInboundReply = mutationGeneric({
  args: {
    externalId: v.string(),
    postExternalId: v.string(),
    replyText: v.string(),
    replyAuthor: v.string(),
    receivedAt: v.number(),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert('inboundReply', {
      platform: 'x',
      externalId: args.externalId,
      postExternalId: args.postExternalId,
      replyText: args.replyText,
      replyAuthor: args.replyAuthor,
      receivedAt: args.receivedAt,
    });
  },
});

export const listByPost = queryGeneric({
  args: { postExternalId: v.string() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query('inboundReply')
      .withIndex('by_post', (q) => q.eq('postExternalId', args.postExternalId))
      .collect();
  },
});
