import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

// Publisher CRUD — issue #9 Slice 1. Shape mirrors
// lib/providers/publisher/types.ts so the client can pass documents through
// untouched. Uses *Generic builders because convex/_generated is not
// committed; it is regenerated by `npx convex dev` at provisioning time.

const PLATFORM_VALIDATOR = v.union(
  v.literal('instagram'),
  v.literal('tiktok'),
  v.literal('x'),
  v.literal('linkedin'),
  v.literal('youtube-shorts'),
  v.literal('xhs'),
  v.literal('douyin'),
  v.literal('bilibili'),
  v.literal('kuaishou'),
  v.literal('pinterest')
);

const STATUS_VALIDATOR = v.union(
  v.literal('draft'),
  v.literal('scheduled'),
  v.literal('published'),
  v.literal('cancelled')
);

interface ScheduledPostDoc {
  _id: unknown;
  wsId?: unknown;
  platform:
    | 'instagram'
    | 'tiktok'
    | 'x'
    | 'linkedin'
    | 'youtube-shorts'
    | 'xhs'
    | 'douyin'
    | 'bilibili'
    | 'kuaishou'
    | 'pinterest';
  mediaUrls: string[];
  caption: string;
  hashtags: string[];
  scheduledAt: string;
  accountId?: string;
  createdAt: number;
  status: 'draft' | 'scheduled' | 'published' | 'cancelled';
  provider?: string;
  externalId?: string;
}

function toRecord(doc: ScheduledPostDoc) {
  return {
    id: String(doc._id),
    platform: doc.platform,
    mediaUrls: doc.mediaUrls,
    caption: doc.caption,
    hashtags: doc.hashtags,
    scheduledAt: doc.scheduledAt,
    accountId: doc.accountId,
    createdAt: doc.createdAt,
    status: doc.status,
    provider: doc.provider,
    externalId: doc.externalId,
  };
}

export const list = queryGeneric({
  args: { wsId: v.optional(v.id('workspace')) },
  handler: async (ctx, args) => {
    const docs: ScheduledPostDoc[] = args.wsId
      ? ((await ctx.db
          .query('scheduledPost')
          .withIndex('by_ws', (q: any) => q.eq('wsId', args.wsId))
          .order('asc')
          .take(500)) as ScheduledPostDoc[])
      : ((await ctx.db.query('scheduledPost').order('asc').take(500)) as ScheduledPostDoc[]);
    return docs.map(toRecord);
  },
});

export const schedule = mutationGeneric({
  args: {
    wsId: v.optional(v.id('workspace')),
    platform: PLATFORM_VALIDATOR,
    mediaUrls: v.array(v.string()),
    caption: v.string(),
    hashtags: v.array(v.string()),
    scheduledAt: v.string(),
    accountId: v.optional(v.string()),
    provider: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    if (args.mediaUrls.length === 0) {
      throw new Error('mediaUrls required');
    }
    const id = await ctx.db.insert('scheduledPost', {
      wsId: args.wsId,
      platform: args.platform,
      mediaUrls: args.mediaUrls,
      caption: args.caption,
      hashtags: args.hashtags,
      scheduledAt: args.scheduledAt,
      accountId: args.accountId,
      provider: args.provider ?? 'preview',
      status: 'scheduled',
      createdAt: Date.now(),
    });
    return String(id);
  },
});

export const cancel = mutationGeneric({
  args: { id: v.id('scheduledPost') },
  handler: async (ctx, args) => {
    // Soft-cancel so the record survives for audit; the UI filters these out
    // of the default list. `list()` returns them so the right-rail can show
    // "cancelled" chips if the creator wants a full history.
    await ctx.db.patch(args.id, { status: 'cancelled' });
  },
});

export const updateStatus = mutationGeneric({
  args: {
    id: v.id('scheduledPost'),
    status: STATUS_VALIDATOR,
    externalId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const patch: { status: typeof args.status; externalId?: string } = {
      status: args.status,
    };
    if (args.externalId !== undefined) patch.externalId = args.externalId;
    await ctx.db.patch(args.id, patch);
  },
});
