import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';
import { STALE_ABORT_ERROR } from '../lib/store/runs.types';
import type { ArtifactKind } from '../lib/tool/registry';

// Capability-run persistence. Shape mirrors lib/store/runs CapabilityRunRecord
// so the client wrapper can pass Convex documents through untouched.
//
// Uses the *Generic builders because convex/_generated is not committed — it
// is regenerated by `npx convex dev` at provisioning time. The loss in type
// precision is acceptable for the log: payloads match the schema validators.

const MAX_RUNS = 50;

const STEP_VALIDATOR = v.union(
  v.literal('prepared'),
  v.literal('sending'),
  v.literal('awaiting'),
  v.literal('received'),
  v.literal('parsing'),
  v.literal('placing'),
  v.literal('done')
);

const RUN_STATUS_VALIDATOR = v.union(
  v.literal('running'),
  v.literal('ok'),
  v.literal('error'),
  v.literal('draft-executor')
);

// Finishing a live run is narrower than storing a run record: draft-executor
// rows are intent records created by stub executors, not completion results.
const FINISH_STATUS_VALIDATOR = v.union(
  v.literal('running'),
  v.literal('ok'),
  v.literal('error')
);

const ARTIFACT_KIND_VALIDATOR = v.union(
  v.literal('image'),
  v.literal('video'),
  v.literal('audio'),
  v.literal('spatial'),
  v.literal('text-overlay')
);

interface RunDoc {
  _id: unknown;
  clientRunId: string;
  definitionId?: string;
  definitionVersion?: number;
  entryRef?: {
    kind: 'tool' | 'workflow' | 'skill';
    id: string;
    version: number;
  };
  artifactKind?: ArtifactKind;
  outputFormat?: 'particle-field' | 'gaussian-splat';
  quality?: 'draft' | 'standard' | 'high';
  sourceMode?: 'selected-image';
  sourceImageShapeId?: string;
  tool: string;
  provider: string;
  model: string;
  prompt: string;
  step?: string;
  rewrittenPrompt?: string;
  rationale?: string;
  aspectRatio?: string;
  imageUrl?: string;
  latencyMs?: number;
  outputs?: unknown;
  status: 'running' | 'ok' | 'error' | 'draft-executor';
  startedAt: number;
  finishedAt?: number;
  error?: string;
  httpStatus?: number;
}

function toRecord(doc: RunDoc) {
  return {
    id: doc.clientRunId,
    tool: doc.tool,
    provider: doc.provider,
    model: doc.model,
    prompt: doc.prompt,
    rewrittenPrompt: doc.rewrittenPrompt,
    rationale: doc.rationale,
    aspectRatio: doc.aspectRatio,
    imageUrl: doc.imageUrl,
    latencyMs: doc.latencyMs,
    status: doc.status,
    step: doc.step,
    startedAt: doc.startedAt,
    finishedAt: doc.finishedAt,
    error: doc.error,
    httpStatus: doc.httpStatus,
    definitionId: doc.definitionId,
    definitionVersion: doc.definitionVersion,
    entryRef: doc.entryRef,
    artifactKind: doc.artifactKind,
    outputFormat: doc.outputFormat,
    quality: doc.quality,
    sourceMode: doc.sourceMode,
    sourceImageShapeId: doc.sourceImageShapeId,
  };
}

export const list = queryGeneric({
  args: { wsId: v.optional(v.string()) },
  handler: async (ctx, args) => {
    const docs: RunDoc[] = args.wsId
      ? ((await ctx.db
          .query('capabilityRun')
          .withIndex('by_ws', (q: any) => q.eq('wsId', args.wsId))
          .order('desc')
          .take(MAX_RUNS)) as RunDoc[])
      : ((await ctx.db.query('capabilityRun').order('desc').take(MAX_RUNS)) as RunDoc[]);
    return docs.map(toRecord);
  },
});

/**
 * Fetch a single capabilityRun row by its client-assigned run ID.
 * Used by the /api/campaigns/[id]/trace endpoint to enrich agentSteps
 * with provider/model/latency data from the ledger.
 * Returns null when the clientRunId is not found.
 */
export const getByClientId = queryGeneric({
  args: { clientRunId: v.string() },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return null;
    return toRecord(doc);
  },
});

async function findByClientId(ctx: any, clientRunId: string): Promise<RunDoc | null> {
  return (await ctx.db
    .query('capabilityRun')
    .withIndex('by_client_run_id', (q: any) => q.eq('clientRunId', clientRunId))
    .unique()) as RunDoc | null;
}

export const start = mutationGeneric({
  args: {
    clientRunId: v.string(),
    wsId: v.optional(v.string()),
    definitionId: v.optional(v.string()),
    definitionVersion: v.optional(v.number()),
    entryRef: v.optional(
      v.object({
        kind: v.union(v.literal('tool'), v.literal('workflow'), v.literal('skill')),
        id: v.string(),
        version: v.number(),
      })
    ),
    artifactKind: v.optional(ARTIFACT_KIND_VALIDATOR),
    outputFormat: v.optional(v.union(v.literal('particle-field'), v.literal('gaussian-splat'))),
    quality: v.optional(v.union(v.literal('draft'), v.literal('standard'), v.literal('high'))),
    sourceMode: v.optional(v.literal('selected-image')),
    sourceImageShapeId: v.optional(v.string()),
    tool: v.string(),
    provider: v.string(),
    model: v.string(),
    prompt: v.string(),
    aspectRatio: v.optional(v.string()),
    status: v.optional(RUN_STATUS_VALIDATOR),
    startedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const existing = await findByClientId(ctx, args.clientRunId);
    if (existing) return args.clientRunId;
    await ctx.db.insert('capabilityRun', {
      clientRunId: args.clientRunId,
      wsId: args.wsId,
      definitionId: args.definitionId,
      definitionVersion: args.definitionVersion,
      entryRef: args.entryRef,
      artifactKind: args.artifactKind,
      outputFormat: args.outputFormat,
      quality: args.quality,
      sourceMode: args.sourceMode,
      sourceImageShapeId: args.sourceImageShapeId,
      tool: args.tool,
      provider: args.provider,
      model: args.model,
      prompt: args.prompt,
      aspectRatio: args.aspectRatio,
      inputs: { prompt: args.prompt, model: args.model, aspectRatio: args.aspectRatio },
      outputs: {},
      startedAt: args.startedAt,
      status: args.status ?? 'running',
    });
    return args.clientRunId;
  },
});

export const step = mutationGeneric({
  args: { clientRunId: v.string(), step: STEP_VALIDATOR },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return;
    await ctx.db.patch(doc._id as any, { step: args.step });
  },
});

export const finish = mutationGeneric({
  args: {
    clientRunId: v.string(),
    status: v.optional(FINISH_STATUS_VALIDATOR),
    provider: v.optional(v.string()),
    model: v.optional(v.string()),
    rewrittenPrompt: v.optional(v.string()),
    rationale: v.optional(v.string()),
    aspectRatio: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    latencyMs: v.optional(v.number()),
    error: v.optional(v.string()),
    httpStatus: v.optional(v.number()),
    finishedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return;
    const { clientRunId: _ignored, ...patch } = args;
    const existingOutputs =
      typeof doc.outputs === 'object' && doc.outputs !== null
        ? (doc.outputs as Record<string, unknown>)
        : {};
    const nextOutputs = {
      ...existingOutputs,
      imageUrl: args.imageUrl ?? doc.imageUrl,
      latencyMs: args.latencyMs ?? doc.latencyMs,
    };
    await ctx.db.patch(doc._id as any, {
      ...patch,
      status: args.status ?? 'ok',
      step: 'done',
      outputs: nextOutputs,
    });
  },
});

export const fail = mutationGeneric({
  args: {
    clientRunId: v.string(),
    error: v.string(),
    httpStatus: v.optional(v.number()),
    finishedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return;
    await ctx.db.patch(doc._id as any, {
      status: 'error',
      step: 'done',
      error: args.error,
      httpStatus: args.httpStatus,
      finishedAt: args.finishedAt,
    });
  },
});

/**
 * Escape hatch for stuck runs. When `runs:finish` throws server-side (the
 * canonical case: an oversized `imageUrl` data URL pre-#102 — see
 * lib/convex/sanitize.ts), the row stays `status:'running'` forever and the
 * composer status indicator counts up indefinitely. This mutation walks all
 * `capabilityRun` rows whose `startedAt` is older than the supplied
 * threshold and marks them as failed so the indicator clears.
 *
 * Safe to call repeatedly. Returns the count of rows it patched so the UI
 * can show "abort N stuck runs" feedback.
 */
export const abortStuck = mutationGeneric({
  args: {
    /** Default threshold: 60 seconds. Anything older than this and still
     *  running is considered stuck. */
    olderThanMs: v.optional(v.number()),
    /** Optional workspace scope. If omitted, walks every workspace. */
    wsId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const threshold = Date.now() - (args.olderThanMs ?? 60_000);
    const docs: RunDoc[] = args.wsId
      ? ((await ctx.db
          .query('capabilityRun')
          .withIndex('by_ws', (q: any) => q.eq('wsId', args.wsId))
          .collect()) as RunDoc[])
      : ((await ctx.db.query('capabilityRun').collect()) as RunDoc[]);
    let aborted = 0;
    for (const doc of docs) {
      if (doc.status !== 'running') continue;
      if (doc.startedAt > threshold) continue;
      await ctx.db.patch(doc._id as any, {
        status: 'error',
        step: 'done',
        error: STALE_ABORT_ERROR,
        finishedAt: Date.now(),
      });
      aborted += 1;
    }
    return { aborted };
  },
});
