import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

// Capability-run persistence. Shape mirrors lib/store/runs CapabilityRunRecord
// so the client wrapper can pass Convex documents through untouched.
//
// Uses the *Generic builders because convex/_generated is not committed — it
// is regenerated by `npx convex dev` at provisioning time. The loss in type
// precision is acceptable for the log: payloads match the schema validators.

const MAX_RUNS = 50;

const STEP_VALIDATOR = v.union(
  v.literal('prepared'),
  v.literal('sending'),
  v.literal('awaiting'),
  v.literal('received'),
  v.literal('parsing'),
  v.literal('placing'),
  v.literal('done')
);

const STATUS_VALIDATOR = v.union(v.literal('running'), v.literal('ok'), v.literal('error'));

interface RunDoc {
  _id: unknown;
  clientRunId: string;
  definitionId?: string;
  definitionVersion?: number;
  entryRef?: {
    kind: 'tool' | 'workflow' | 'skill';
    id: string;
    version: number;
  };
  tool: string;
  provider: string;
  model: string;
  prompt: string;
  step?: string;
  rewrittenPrompt?: string;
  rationale?: string;
  aspectRatio?: string;
  imageUrl?: string;
  latencyMs?: number;
  outputs?: unknown;
  status: 'running' | 'ok' | 'error';
  startedAt: number;
  finishedAt?: number;
  error?: string;
  httpStatus?: number;
}

function toRecord(doc: RunDoc) {
  return {
    id: doc.clientRunId,
    tool: doc.tool,
    provider: doc.provider,
    model: doc.model,
    prompt: doc.prompt,
    rewrittenPrompt: doc.rewrittenPrompt,
    rationale: doc.rationale,
    aspectRatio: doc.aspectRatio,
    imageUrl: doc.imageUrl,
    latencyMs: doc.latencyMs,
    status: doc.status,
    step: doc.step,
    startedAt: doc.startedAt,
    finishedAt: doc.finishedAt,
    error: doc.error,
    httpStatus: doc.httpStatus,
    definitionId: doc.definitionId,
    definitionVersion: doc.definitionVersion,
    entryRef: doc.entryRef,
  };
}

export const list = queryGeneric({
  args: { wsId: v.optional(v.id('workspace')) },
  handler: async (ctx, args) => {
    const docs: RunDoc[] = args.wsId
      ? ((await ctx.db
          .query('capabilityRun')
          .withIndex('by_ws', (q: any) => q.eq('wsId', args.wsId))
          .order('desc')
          .take(MAX_RUNS)) as RunDoc[])
      : ((await ctx.db.query('capabilityRun').order('desc').take(MAX_RUNS)) as RunDoc[]);
    return docs.map(toRecord);
  },
});

async function findByClientId(ctx: any, clientRunId: string): Promise<RunDoc | null> {
  return (await ctx.db
    .query('capabilityRun')
    .withIndex('by_client_run_id', (q: any) => q.eq('clientRunId', clientRunId))
    .unique()) as RunDoc | null;
}

export const start = mutationGeneric({
  args: {
    clientRunId: v.string(),
    wsId: v.optional(v.id('workspace')),
    definitionId: v.optional(v.string()),
    definitionVersion: v.optional(v.number()),
    entryRef: v.optional(
      v.object({
        kind: v.union(v.literal('tool'), v.literal('workflow'), v.literal('skill')),
        id: v.string(),
        version: v.number(),
      })
    ),
    tool: v.string(),
    provider: v.string(),
    model: v.string(),
    prompt: v.string(),
    aspectRatio: v.optional(v.string()),
    startedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const existing = await findByClientId(ctx, args.clientRunId);
    if (existing) return args.clientRunId;
    await ctx.db.insert('capabilityRun', {
      clientRunId: args.clientRunId,
      wsId: args.wsId,
      definitionId: args.definitionId,
      definitionVersion: args.definitionVersion,
      entryRef: args.entryRef,
      tool: args.tool,
      provider: args.provider,
      model: args.model,
      prompt: args.prompt,
      aspectRatio: args.aspectRatio,
      inputs: { prompt: args.prompt, model: args.model, aspectRatio: args.aspectRatio },
      outputs: {},
      startedAt: args.startedAt,
      status: 'running',
    });
    return args.clientRunId;
  },
});

export const step = mutationGeneric({
  args: { clientRunId: v.string(), step: STEP_VALIDATOR },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return;
    await ctx.db.patch(doc._id as any, { step: args.step });
  },
});

export const finish = mutationGeneric({
  args: {
    clientRunId: v.string(),
    status: v.optional(STATUS_VALIDATOR),
    provider: v.optional(v.string()),
    model: v.optional(v.string()),
    rewrittenPrompt: v.optional(v.string()),
    rationale: v.optional(v.string()),
    aspectRatio: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    latencyMs: v.optional(v.number()),
    error: v.optional(v.string()),
    httpStatus: v.optional(v.number()),
    finishedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return;
    const { clientRunId: _ignored, ...patch } = args;
    const existingOutputs =
      typeof doc.outputs === 'object' && doc.outputs !== null
        ? (doc.outputs as Record<string, unknown>)
        : {};
    const nextOutputs = {
      ...existingOutputs,
      imageUrl: args.imageUrl ?? doc.imageUrl,
      latencyMs: args.latencyMs ?? doc.latencyMs,
    };
    await ctx.db.patch(doc._id as any, {
      ...patch,
      status: args.status ?? 'ok',
      step: 'done',
      outputs: nextOutputs,
    });
  },
});

export const fail = mutationGeneric({
  args: {
    clientRunId: v.string(),
    error: v.string(),
    httpStatus: v.optional(v.number()),
    finishedAt: v.number(),
  },
  handler: async (ctx, args) => {
    const doc = await findByClientId(ctx, args.clientRunId);
    if (!doc) return;
    await ctx.db.patch(doc._id as any, {
      status: 'error',
      step: 'done',
      error: args.error,
      httpStatus: args.httpStatus,
      finishedAt: args.finishedAt,
    });
  },
});
