import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

// Signal-subscription persistence. Shape mirrors lib/signals/types.ts so the
// client store can pass Convex documents through untouched.
//
// Uses the *Generic builders because convex/_generated is not committed — it
// is regenerated by `npx convex dev` at provisioning time. Acceptable for the
// CRUD surface: payloads still match the schema validators.

const KIND_VALIDATOR = v.union(
  v.literal('keyword'),
  v.literal('hashtag'),
  v.literal('account')
);

const HASHTAG_STRIP = /^#+/;
const HANDLE_STRIP = /^@+/;

function normalizeValue(kind: 'keyword' | 'hashtag' | 'account', raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return '';
  if (kind === 'hashtag') return trimmed.replace(HASHTAG_STRIP, '');
  if (kind === 'account') return trimmed.replace(HANDLE_STRIP, '');
  return trimmed;
}

interface SignalDoc {
  _id: unknown;
  wsId?: unknown;
  kind: 'keyword' | 'hashtag' | 'account';
  value: string;
  addedAt: number;
  lastCheckedAt?: number;
  mutedUntil?: number;
}

function toRecord(doc: SignalDoc) {
  return {
    id: String(doc._id),
    kind: doc.kind,
    value: doc.value,
    addedAt: doc.addedAt,
    lastCheckedAt: doc.lastCheckedAt,
    mutedUntil: doc.mutedUntil,
  };
}

export const list = queryGeneric({
  args: { wsId: v.optional(v.id('workspace')) },
  handler: async (ctx, args) => {
    const docs: SignalDoc[] = args.wsId
      ? ((await ctx.db
          .query('signalSubscription')
          .withIndex('by_ws', (q: any) => q.eq('wsId', args.wsId))
          .order('asc')
          .take(500)) as SignalDoc[])
      : ((await ctx.db.query('signalSubscription').order('asc').take(500)) as SignalDoc[]);
    return docs.map(toRecord);
  },
});

export const add = mutationGeneric({
  args: {
    wsId: v.optional(v.id('workspace')),
    kind: KIND_VALIDATOR,
    value: v.string(),
  },
  handler: async (ctx, args) => {
    const normalized = normalizeValue(args.kind, args.value);
    if (!normalized) throw new Error('signal value required');
    const existing = args.wsId
      ? ((await ctx.db
          .query('signalSubscription')
          .withIndex('by_ws', (q: any) => q.eq('wsId', args.wsId))
          .collect()) as SignalDoc[])
      : ((await ctx.db.query('signalSubscription').collect()) as SignalDoc[]);
    const dup = existing.find((d) => d.kind === args.kind && d.value === normalized);
    if (dup) return String(dup._id);
    const id = await ctx.db.insert('signalSubscription', {
      wsId: args.wsId,
      kind: args.kind,
      value: normalized,
      addedAt: Date.now(),
    });
    return String(id);
  },
});

export const remove = mutationGeneric({
  args: { id: v.id('signalSubscription') },
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id);
  },
});

export const mute = mutationGeneric({
  args: {
    id: v.id('signalSubscription'),
    mutedUntil: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const fallback = Date.now() + 1000 * 60 * 60 * 24 * 365 * 5; // ~5y = "indefinite"
    await ctx.db.patch(args.id, { mutedUntil: args.mutedUntil ?? fallback });
  },
});

export const unmute = mutationGeneric({
  args: { id: v.id('signalSubscription') },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.id, { mutedUntil: undefined });
  },
});
