import { mutationGeneric, queryGeneric } from 'convex/server';
import { v } from 'convex/values';

/**
 * textOverlay persistence for the multilingual text-overlay umbrella (#66).
 * Each `create` / `update` / `delete` records a `capabilityRun` row with
 * `entryRef: { kind: 'tool', id: 'text-apply', version: 1 }` so the agent
 * can replay the edit against a different layer or aspect.
 *
 * Uses the *Generic builders because convex/_generated is not committed — it
 * is regenerated by `npx convex dev` at provisioning time. Handler logic
 * lives in plain async functions so unit tests can drive them with an
 * in-memory ctx (see tests/unit/convex-text-overlay.test.ts).
 */

export const TEXT_APPLY_ENTRY_REF = {
  kind: 'tool',
  id: 'text-apply',
  version: 1,
} as const;

const CONTENT_VALIDATOR = v.any();
const STYLE_VALIDATOR = v.any();
const PLACEMENT_VALIDATOR = v.any();

export interface TextOverlayCtx {
  db: {
    insert(table: string, doc: Record<string, unknown>): Promise<string>;
    patch(id: string, patch: Record<string, unknown>): Promise<void>;
    delete(id: string): Promise<void>;
    get(id: string): Promise<Record<string, unknown> | null>;
  };
}

interface CreateArgs {
  wsId: string;
  artboardId: string;
  content: Record<string, string>;
  activeLanguage: string;
  style: Record<string, unknown>;
  placement: Record<string, unknown>;
  smartPlacement?: boolean;
  protectedElementIds?: string[];
}

interface UpdateArgs {
  id: string;
  content?: Record<string, string>;
  activeLanguage?: string;
  style?: Record<string, unknown>;
  placement?: Record<string, unknown>;
  smartPlacement?: boolean;
  protectedElementIds?: string[];
}

interface DeleteArgs {
  id: string;
}

async function recordCapabilityRun(
  ctx: TextOverlayCtx,
  action: 'create' | 'update' | 'delete',
  wsId: string | undefined,
  inputs: Record<string, unknown>,
  outputs: Record<string, unknown>,
  beforeSnapshotRef: string | null
): Promise<string> {
  const now = Date.now();
  const clientRunId = `text-apply_${action}_${now}_${Math.random().toString(36).slice(2, 8)}`;
  await ctx.db.insert('capabilityRun', {
    clientRunId,
    ...(wsId ? { wsId } : {}),
    entryRef: TEXT_APPLY_ENTRY_REF,
    artifactKind: 'text-overlay',
    tool: 'text-apply',
    provider: 'stub',
    model: 'stub',
    prompt: '',
    inputs,
    outputs,
    beforeSnapshotRef,
    afterSnapshotRef: null,
    startedAt: now,
    finishedAt: now,
    status: 'draft-executor',
  });
  return clientRunId;
}

export async function createTextOverlayHandler(
  ctx: TextOverlayCtx,
  args: CreateArgs
): Promise<string> {
  const now = Date.now();
  const clientRunId = await recordCapabilityRun(
    ctx,
    'create',
    args.wsId,
    { ...args },
    { artboardId: args.artboardId },
    null
  );
  const id = await ctx.db.insert('textOverlay', {
    wsId: args.wsId,
    artboardId: args.artboardId,
    content: args.content,
    activeLanguage: args.activeLanguage,
    style: args.style,
    placement: args.placement,
    smartPlacement: args.smartPlacement ?? false,
    protectedElementIds: args.protectedElementIds ?? [],
    provenance: { capabilityRunId: clientRunId },
    createdAt: now,
    updatedAt: now,
  });
  return String(id);
}

export async function updateTextOverlayHandler(
  ctx: TextOverlayCtx,
  args: UpdateArgs
): Promise<void> {
  const existing = await ctx.db.get(args.id);
  if (!existing) return;
  const wsId = typeof existing.wsId === 'string' ? existing.wsId : undefined;
  const patch: Record<string, unknown> = { updatedAt: Date.now() };
  if (args.content !== undefined) patch.content = args.content;
  if (args.activeLanguage !== undefined) patch.activeLanguage = args.activeLanguage;
  if (args.style !== undefined) patch.style = args.style;
  if (args.placement !== undefined) patch.placement = args.placement;
  if (args.smartPlacement !== undefined) patch.smartPlacement = args.smartPlacement;
  if (args.protectedElementIds !== undefined) patch.protectedElementIds = args.protectedElementIds;
  // T1 stores the previous overlay row id as a placeholder until the real
  // executor records canvas snapshots in T4/T5/T9.
  const beforeSnapshotRef = args.id;
  await recordCapabilityRun(
    ctx,
    'update',
    wsId,
    { ...args },
    { id: args.id },
    beforeSnapshotRef
  );
  await ctx.db.patch(args.id, patch);
}

export async function deleteTextOverlayHandler(
  ctx: TextOverlayCtx,
  args: DeleteArgs
): Promise<void> {
  const existing = await ctx.db.get(args.id);
  if (!existing) return;
  const wsId = typeof existing.wsId === 'string' ? existing.wsId : undefined;
  // T1 stores the previous overlay row id as a placeholder until the real
  // executor records canvas snapshots in T4/T5/T9.
  const beforeSnapshotRef = args.id;
  await recordCapabilityRun(ctx, 'delete', wsId, { id: args.id }, {}, beforeSnapshotRef);
  await ctx.db.delete(args.id);
}

export const createTextOverlay = mutationGeneric({
  args: {
    wsId: v.id('workspace'),
    artboardId: v.string(),
    content: CONTENT_VALIDATOR,
    activeLanguage: v.string(),
    style: STYLE_VALIDATOR,
    placement: PLACEMENT_VALIDATOR,
    smartPlacement: v.optional(v.boolean()),
    protectedElementIds: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) =>
    createTextOverlayHandler(ctx as unknown as TextOverlayCtx, args as unknown as CreateArgs),
});

export const updateTextOverlay = mutationGeneric({
  args: {
    id: v.id('textOverlay'),
    content: v.optional(CONTENT_VALIDATOR),
    activeLanguage: v.optional(v.string()),
    style: v.optional(STYLE_VALIDATOR),
    placement: v.optional(PLACEMENT_VALIDATOR),
    smartPlacement: v.optional(v.boolean()),
    protectedElementIds: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) =>
    updateTextOverlayHandler(ctx as unknown as TextOverlayCtx, args as unknown as UpdateArgs),
});

export const deleteTextOverlay = mutationGeneric({
  args: { id: v.id('textOverlay') },
  handler: async (ctx, args) =>
    deleteTextOverlayHandler(ctx as unknown as TextOverlayCtx, args as unknown as DeleteArgs),
});

export const listByWorkspace = queryGeneric({
  args: { wsId: v.id('workspace') },
  handler: async (ctx, args) => {
    const docs = await ctx.db
      .query('textOverlay')
      .withIndex('by_wsId', (q: any) => q.eq('wsId', args.wsId))
      .collect();
    return docs;
  },
});
