import {
  createDoubleExposureSceneSpec,
  type DoubleExposureMediaSource,
  type DoubleExposureSceneInput,
  type DoubleExposureSceneSpec,
} from '@/lib/video/doubleExposure';

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeAttribute(value: string) {
  return escapeHtml(value).replaceAll("'", '&#39;');
}

function renderMediaTag(
  id: string,
  media: DoubleExposureMediaSource,
  className = 'de-source'
) {
  const attrs = Object.entries({
    id,
    class: className,
    src: media.url,
    ...(media.posterUrl ? { poster: media.posterUrl } : {}),
    ...(media.kind === 'video'
      ? {
          muted: 'true',
          playsinline: 'true',
          preload: 'auto',
          loop: 'true',
        }
      : {
          loading: 'eager',
          decoding: 'sync',
        }),
  })
    .map(([key, value]) => `${key}="${escapeAttribute(value)}"`)
    .join(' ');

  return media.kind === 'video' ? `<video ${attrs}></video>` : `<img ${attrs} />`;
}

function splitTitleUnits(title: string) {
  return Array.from(title).map((character) => (character === ' ' ? '\u00a0' : character));
}

function renderTitleMarkup(title: string, effectId: string) {
  const units = splitTitleUnits(title);
  return [
    `<h1 class="de-title" data-animate-text="${escapeAttribute(effectId)}" aria-label="${escapeAttribute(title)}">`,
    ...units.map((character, index) =>
      `<span class="de-title-unit" style="--de-unit-index:${index}">${escapeHtml(character)}</span>`
    ),
    '</h1>',
  ].join('');
}

export function renderHyperframesDoubleExposureComposition(
  spec: DoubleExposureSceneSpec
) {
  const compositionId = spec.payload.id;
  const payload = spec.payload;
  const isClassicLook = payload.look === 'classic';
  const rootClasses = [
    'de-root',
    isClassicLook ? 'de-look-classic' : 'de-look-cinematic',
    !payload.preview.effectInitiallyEnabled ? 'de-effect-disabled' : '',
  ]
    .filter(Boolean)
    .join(' ');
  const toggleLabel = payload.preview.effectInitiallyEnabled ? 'Effect On' : 'Effect Off';
  const specJson = JSON.stringify(spec);
  const audioAttrs = payload.audio
    ? {
        id: 'de-audio',
        src: payload.audio.url,
        'data-start': '0',
        'data-duration': String(spec.durationSec),
        'data-track-index': '2',
        'data-volume': String(payload.audio.volume),
        preload: 'auto',
      }
    : null;

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width,initial-scale=1" />',
    `  <title>${escapeHtml(spec.title ?? 'Double Exposure Intro')}</title>`,
    '  <style>',
    `    :root { color-scheme: ${isClassicLook ? 'light' : 'dark'}; }`,
    `    html, body { margin: 0; width: 100%; height: 100%; background: ${payload.grade.backgroundFill}; }`,
    '    body { overflow: hidden; font-family: "Helvetica Neue", Arial, sans-serif; }',
    '    #root { width: 100%; height: 100%; }',
    `    [data-composition-id="${escapeAttribute(compositionId)}"] {`,
    '      position: relative;',
    '      width: 100%;',
    '      height: 100%;',
    `      background: ${payload.grade.backgroundFill};`,
    '      overflow: hidden;',
    '      isolation: isolate;',
    '    }',
    '    .de-canvas { position: absolute; inset: 0; width: 100%; height: 100%; display: block; }',
    '    .de-source-bank { position: absolute; width: 1px; height: 1px; opacity: 0; pointer-events: none; inset: auto; overflow: hidden; }',
    '    .de-source { position: absolute; width: 1px; height: 1px; left: -9999px; top: -9999px; }',
    '    .de-overlay {',
    '      position: absolute;',
    '      inset: 0;',
    '      pointer-events: none;',
    '      display: flex;',
    '      flex-direction: column;',
    '      justify-content: flex-end;',
    '      padding: 96px 108px 92px;',
    '      box-sizing: border-box;',
    '      z-index: 5;',
    '      color: rgba(244, 247, 251, 0.94);',
    '    }',
    '    .de-root.de-look-classic .de-overlay {',
    '      padding: 78px 88px 72px;',
    '      color: rgba(22, 26, 34, 0.92);',
    '      justify-content: flex-end;',
    '    }',
    '    .de-kicker {',
    '      margin: 0 0 18px;',
    '      font-size: 13px;',
    '      font-weight: 600;',
    '      letter-spacing: 0.24em;',
    '      text-transform: uppercase;',
    '      opacity: 0.76;',
    '    }',
    '    .de-root.de-look-classic .de-kicker {',
    '      margin-bottom: 14px;',
    '      font-size: 11px;',
    '      letter-spacing: 0.2em;',
    '      opacity: 0.52;',
    '    }',
    '    .de-title {',
    '      margin: 0;',
    '      max-width: min(11ch, 60vw);',
    '      font-family: "Avenir Next Condensed", "Arial Narrow Bold", "Helvetica Neue", sans-serif;',
    '      font-size: clamp(56px, 9vw, 136px);',
    '      line-height: 0.94;',
    '      letter-spacing: -0.045em;',
    '      text-transform: uppercase;',
    '      text-wrap: balance;',
    '      text-shadow: 0 0 24px rgba(244, 247, 251, 0.1);',
    '    }',
    '    .de-root.de-look-classic .de-title {',
    '      max-width: min(8ch, 44vw);',
    '      font-size: clamp(48px, 7vw, 112px);',
    '      line-height: 0.98;',
    '      letter-spacing: -0.04em;',
    '      text-shadow: none;',
    '    }',
    '    .de-title-unit { display: inline-block; white-space: pre; }',
    '    .de-title[data-animate-text="soft-blur-in"] .de-title-unit {',
    '      opacity: 0;',
    '      transform: translate3d(0, 9.28px, 0);',
    '      filter: blur(12px);',
    '      animation: de-soft-blur-in 648ms cubic-bezier(0.22, 1, 0.36, 1) forwards;',
    '      animation-delay: calc(var(--de-unit-index) * 18ms + 120ms);',
    '    }',
    '    .de-body {',
    '      margin: 18px 0 0;',
    '      max-width: 32ch;',
    '      font-size: clamp(15px, 1.6vw, 22px);',
    '      line-height: 1.45;',
    '      letter-spacing: 0.015em;',
    '      color: rgba(244, 247, 251, 0.7);',
    '      opacity: 0;',
    '      transform: translate3d(0, 18px, 0);',
    '      animation: de-copy-rise 720ms cubic-bezier(0.22, 1, 0.36, 1) 360ms forwards;',
    '    }',
    '    .de-root.de-look-classic .de-body {',
    '      margin-top: 14px;',
    '      max-width: 24ch;',
    '      font-size: clamp(14px, 1.2vw, 18px);',
    '      line-height: 1.42;',
    '      color: rgba(22, 26, 34, 0.6);',
    '    }',
    '    .de-compare-toggle {',
    '      position: absolute;',
    '      top: 72px;',
    '      right: 84px;',
    '      z-index: 6;',
    '      border: 1px solid rgba(244,247,251,0.16);',
    '      background: rgba(7, 10, 20, 0.74);',
    '      color: rgba(244,247,251,0.92);',
    '      padding: 12px 16px;',
    '      border-radius: 999px;',
    '      font: 600 12px/1 "Helvetica Neue", Arial, sans-serif;',
    '      letter-spacing: 0.18em;',
    '      text-transform: uppercase;',
    '      cursor: pointer;',
    '      backdrop-filter: blur(12px);',
    '      transition: background 160ms ease, border-color 160ms ease, color 160ms ease;',
    '    }',
    '    .de-compare-toggle:hover { background: rgba(12, 16, 31, 0.92); border-color: rgba(244,247,251,0.28); }',
    '    .de-root.de-look-classic .de-compare-toggle {',
    '      top: 44px;',
    '      right: 48px;',
    '      border-color: rgba(22,26,34,0.12);',
    '      background: rgba(255, 255, 255, 0.76);',
    '      color: rgba(22, 26, 34, 0.82);',
    '      backdrop-filter: blur(10px);',
    '      box-shadow: 0 10px 28px rgba(22, 26, 34, 0.08);',
    '    }',
    '    .de-root.de-look-classic .de-compare-toggle:hover { background: rgba(255, 255, 255, 0.92); border-color: rgba(22,26,34,0.2); }',
    '    .de-compare-toggle[hidden] { display: none; }',
    '    .de-grain, .de-letterbox { position: absolute; inset: 0; pointer-events: none; z-index: 4; }',
    '    .de-grain {',
    `      opacity: ${payload.grade.grainOpacity.toFixed(3)};`,
    '      background-image:',
    '        radial-gradient(circle at 12% 18%, rgba(255,255,255,0.7) 0.55px, transparent 0.7px),',
    '        radial-gradient(circle at 78% 62%, rgba(255,255,255,0.3) 0.55px, transparent 0.7px);',
    '      background-size: 7px 7px, 9px 9px;',
    '      mix-blend-mode: soft-light;',
    '    }',
    '    .de-root.de-look-classic .de-grain { mix-blend-mode: multiply; }',
    '    .de-letterbox::before, .de-letterbox::after {',
    '      content: "";',
    '      position: absolute;',
    '      left: 0;',
    '      right: 0;',
    '      height: 52px;',
    '      background: rgba(2, 4, 10, 0.88);',
    '      box-shadow: 0 18px 42px rgba(2, 4, 10, 0.4);',
    '    }',
    '    .de-letterbox::before { top: 0; }',
    '    .de-letterbox::after { bottom: 0; box-shadow: 0 -18px 42px rgba(2, 4, 10, 0.4); }',
    '    .de-root.de-look-classic .de-letterbox { display: none; }',
    '    .de-accessibility { position: absolute; width: 1px; height: 1px; padding: 0; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }',
    '    @keyframes de-soft-blur-in {',
    '      0% { opacity: 0; transform: translate3d(0, 9.28px, 0); filter: blur(12px); }',
    '      100% { opacity: 1; transform: translate3d(0, 0, 0); filter: blur(0px); }',
    '    }',
    '    @keyframes de-copy-rise {',
    '      0% { opacity: 0; transform: translate3d(0, 18px, 0); filter: blur(8px); }',
    '      100% { opacity: 1; transform: translate3d(0, 0, 0); filter: blur(0px); }',
    '    }',
    '    @media (max-width: 1100px) {',
    '      .de-overlay { padding: 76px 52px 72px; }',
    '      .de-root.de-look-classic .de-overlay { padding: 56px 36px 44px; }',
    '      .de-kicker { margin-bottom: 14px; font-size: 11px; }',
    '      .de-body { max-width: 28ch; }',
    '      .de-compare-toggle { top: 54px; right: 52px; padding: 10px 13px; font-size: 11px; }',
    '      .de-root.de-look-classic .de-compare-toggle { top: 26px; right: 26px; }',
    '      .de-letterbox::before, .de-letterbox::after { height: 34px; }',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    `  <div id="root" class="${escapeAttribute(rootClasses)}" data-composition-id="${escapeAttribute(compositionId)}" data-start="0" data-duration="${spec.durationSec}" data-width="${spec.size.w}" data-height="${spec.size.h}">`,
    '    <canvas id="de-canvas" class="de-canvas"></canvas>',
    '    <div class="de-source-bank" aria-hidden="true">',
    `      ${renderMediaTag('de-source-subject', payload.subject)}`,
    `      ${renderMediaTag('de-source-exposure', payload.exposure)}`,
    `      ${renderMediaTag('de-source-background', payload.background)}`,
    ...payload.atmosphere.map((media, index) =>
      `      ${renderMediaTag(`de-source-atmosphere-${index}`, media)}`
    ),
    '    </div>',
    `    <button type="button" id="de-compare-toggle" class="de-compare-toggle"${payload.preview.allowEffectToggle ? '' : ' hidden'}>${escapeHtml(toggleLabel)}</button>`,
    '    <div class="de-overlay">',
    `      <p class="de-kicker">${escapeHtml(payload.overlay.kicker)}</p>`,
    `      ${renderTitleMarkup(payload.overlay.title, payload.overlay.titleEffectId)}`,
    `      <p class="de-body">${escapeHtml(payload.overlay.body)}</p>`,
    '    </div>',
    '    <div class="de-grain"></div>',
    '    <div class="de-letterbox"></div>',
    `    <div class="de-accessibility">${escapeHtml(payload.overlay.title)}</div>`,
    audioAttrs ? `    <audio ${Object.entries(audioAttrs).map(([key, value]) => `${key}="${escapeAttribute(value)}"`).join(' ')}></audio>` : '',
    '  </div>',
    '  <script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js"></script>',
    '  <script>',
    `    const spec = ${specJson};`,
    '    const root = document.querySelector("[data-composition-id]");',
    '    const canvas = document.getElementById("de-canvas");',
    '    const ctx = canvas.getContext("2d");',
    '    const subjectNode = document.getElementById("de-source-subject");',
    '    const exposureNode = document.getElementById("de-source-exposure");',
    '    const backgroundNode = document.getElementById("de-source-background");',
    '    const atmosphereNodes = spec.payload.atmosphere.map((_, index) => document.getElementById(`de-source-atmosphere-${index}`));',
    '    const compareToggle = document.getElementById("de-compare-toggle");',
    '    const subjectCanvas = document.createElement("canvas");',
    '    const subjectCtx = subjectCanvas.getContext("2d", { willReadFrequently: true });',
    '    const matteCanvas = document.createElement("canvas");',
    '    const matteCtx = matteCanvas.getContext("2d", { willReadFrequently: true });',
    '    const featherCanvas = document.createElement("canvas");',
    '    const featherCtx = featherCanvas.getContext("2d");',
    '    const exposureCanvas = document.createElement("canvas");',
    '    const exposureCtx = exposureCanvas.getContext("2d");',
    '    const shellCanvas = document.createElement("canvas");',
    '    const shellCtx = shellCanvas.getContext("2d");',
    '    const glowCanvas = document.createElement("canvas");',
    '    const glowCtx = glowCanvas.getContext("2d");',
    '    const state = {',
    '      started: false,',
    '      previewStart: 0,',
    '      subjectFloatY: 0,',
    `      effectEnabled: ${payload.preview.effectInitiallyEnabled ? 'true' : 'false'},`,
    '    };',
    '    const motionEnabled = spec.payload.preview.motionEnabled;',
    '    const isClassicLook = spec.payload.look === "classic";',
    '    function clamp(value, min, max) { return Math.min(max, Math.max(min, value)); }',
    '    function lerp(a, b, t) { return a + (b - a) * t; }',
    '    function easeOutCubic(t) { return 1 - Math.pow(1 - t, 3); }',
    '    function easeInCubic(t) { return t * t * t; }',
    '    function easeInOutSine(t) { return -(Math.cos(Math.PI * t) - 1) / 2; }',
    '    function resizeCanvases() {',
    '      [canvas, subjectCanvas, matteCanvas, featherCanvas, exposureCanvas, shellCanvas, glowCanvas].forEach((entry) => {',
    '        entry.width = spec.size.w;',
    '        entry.height = spec.size.h;',
    '      });',
    '    }',
    '    function getMediaSize(media) {',
    '      return {',
    '        width: media.videoWidth || media.naturalWidth || spec.size.w,',
    '        height: media.videoHeight || media.naturalHeight || spec.size.h,',
    '      };',
    '    }',
    '    function isRenderable(media) {',
    '      if (!media) return false;',
    '      if (media.tagName === "VIDEO") return media.readyState >= 2;',
    '      return Boolean(media.complete);',
    '    }',
    '    function drawMedia(targetCtx, media, config) {',
    '      if (!isRenderable(media)) return;',
    '      const mediaSize = getMediaSize(media);',
    '      if (!mediaSize.width || !mediaSize.height) return;',
    '      const fit = config.fit || "cover";',
    '      const baseScale = fit === "contain"',
    '        ? Math.min(spec.size.w / mediaSize.width, spec.size.h / mediaSize.height)',
    '        : Math.max(spec.size.w / mediaSize.width, spec.size.h / mediaSize.height);',
    '      const drawScale = baseScale * (config.scale || 1);',
    '      const drawWidth = mediaSize.width * drawScale;',
    '      const drawHeight = mediaSize.height * drawScale;',
    '      const drawX = (spec.size.w - drawWidth) * (config.anchorX ?? 0.5) + (config.offsetX || 0);',
    '      const drawY = (spec.size.h - drawHeight) * (config.anchorY ?? 0.5) + (config.offsetY || 0);',
    '      targetCtx.save();',
    '      targetCtx.globalAlpha = config.alpha ?? 1;',
    '      targetCtx.filter = config.filter || "none";',
    '      targetCtx.drawImage(media, drawX, drawY, drawWidth, drawHeight);',
    '      targetCtx.restore();',
    '    }',
    '    function buildMatte() {',
    '      const keying = spec.payload.keying;',
    '      const subjectLayout = spec.payload.layout.subject;',
    '      subjectCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      drawMedia(subjectCtx, subjectNode, {',
    '        fit: spec.payload.subject.fit,',
    '        scale: subjectLayout.scale,',
    '        anchorX: subjectLayout.anchorX,',
    '        anchorY: subjectLayout.anchorY,',
    '        offsetX: subjectLayout.offsetXPx,',
    '        offsetY: subjectLayout.offsetYPx + state.subjectFloatY,',
    '      });',
    '      const sourceData = subjectCtx.getImageData(0, 0, spec.size.w, spec.size.h);',
    '      const pixels = sourceData.data;',
    '      for (let index = 0; index < pixels.length; index += 4) {',
    '        const intensity = Math.max(pixels[index], pixels[index + 1], pixels[index + 2]);',
    '        const alpha = pixels[index + 3] * clamp((intensity - keying.threshold) / keying.softness, 0, 1);',
    '        pixels[index] = 255;',
    '        pixels[index + 1] = 255;',
    '        pixels[index + 2] = 255;',
    '        pixels[index + 3] = alpha;',
    '      }',
    '      matteCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      matteCtx.putImageData(sourceData, 0, 0);',
    '      featherCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      featherCtx.save();',
    '      featherCtx.filter = keying.featherPx > 0 ? `blur(${keying.featherPx}px)` : "none";',
    '      featherCtx.drawImage(matteCanvas, 0, 0);',
    '      featherCtx.restore();',
    '      return featherCanvas;',
    '    }',
    '    function drawBackground(elapsedSec) {',
    '      const layout = spec.payload.layout.background;',
    '      const motion = spec.payload.animation;',
    '      const drift = easeInOutSine(clamp(elapsedSec / Math.max(spec.durationSec, 0.001), 0, 1));',
    '      const bgScale = lerp(motion.backgroundScaleFrom, motion.backgroundScaleTo, drift) * layout.scale;',
    '      const bgOffsetX = Math.sin(elapsedSec * 0.48) * motion.driftXMaxPx * 0.36 + layout.offsetXPx;',
    '      const bgOffsetY = Math.cos(elapsedSec * 0.33) * motion.driftYMaxPx * 0.32 + layout.offsetYPx;',
    '      if (isClassicLook) {',
    '        drawMedia(ctx, backgroundNode, {',
    '          fit: spec.payload.background.fit,',
    '          scale: bgScale,',
    '          anchorX: layout.anchorX,',
    '          anchorY: layout.anchorY,',
    '          offsetX: bgOffsetX * 0.5,',
    '          offsetY: bgOffsetY * 0.5,',
    '          alpha: state.effectEnabled ? spec.payload.grade.backgroundOpacity : 0.03,',
    '          filter: "grayscale(0.2) saturate(0.6) brightness(1.16) contrast(0.82) blur(24px)",',
    '        });',
    '        const paperWash = ctx.createLinearGradient(0, 0, spec.size.w, spec.size.h);',
    '        paperWash.addColorStop(0, "rgba(255,255,255,0.82)");',
    '        paperWash.addColorStop(0.45, "rgba(244,239,233,0.28)");',
    '        paperWash.addColorStop(1, "rgba(255,255,255,0.76)");',
    '        ctx.fillStyle = paperWash;',
    '        ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        const warmBloom = ctx.createRadialGradient(spec.size.w * 0.78, spec.size.h * 0.62, spec.size.w * 0.04, spec.size.w * 0.78, spec.size.h * 0.62, spec.size.w * 0.44);',
    '        warmBloom.addColorStop(0, `${spec.payload.grade.warmTint}2e`);',
    '        warmBloom.addColorStop(1, "rgba(255,255,255,0)");',
    '        ctx.fillStyle = warmBloom;',
    '        ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        return;',
    '      }',
    '      drawMedia(ctx, backgroundNode, {',
    '        fit: spec.payload.background.fit,',
    '        scale: bgScale,',
    '        anchorX: layout.anchorX,',
    '        anchorY: layout.anchorY,',
    '        offsetX: bgOffsetX,',
    '        offsetY: bgOffsetY,',
    '        alpha: state.effectEnabled ? spec.payload.grade.backgroundOpacity : Math.max(0.14, spec.payload.grade.backgroundOpacity * 0.66),',
    '        filter: "blur(42px) saturate(0.78) brightness(0.46) contrast(1.08)",',
    '      });',
    '      const coolWash = ctx.createRadialGradient(spec.size.w * 0.18, spec.size.h * 0.28, spec.size.w * 0.03, spec.size.w * 0.18, spec.size.h * 0.28, spec.size.w * 0.56);',
    '      coolWash.addColorStop(0, `${spec.payload.grade.coolTint}40`);',
    '      coolWash.addColorStop(1, "rgba(5,8,19,0)");',
    '      ctx.fillStyle = coolWash;',
    '      ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '      const warmWash = ctx.createRadialGradient(spec.size.w * 0.78, spec.size.h * 0.46, spec.size.w * 0.05, spec.size.w * 0.78, spec.size.h * 0.46, spec.size.w * 0.52);',
    '      warmWash.addColorStop(0, `${spec.payload.grade.warmTint}33`);',
    '      warmWash.addColorStop(1, "rgba(5,8,19,0)");',
    '      ctx.fillStyle = warmWash;',
    '      ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '      ctx.fillStyle = "rgba(5,8,19,0.42)";',
    '      ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '    }',
    '    function drawSubjectShell(matteLayer, reveal) {',
    '      shellCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      shellCtx.drawImage(subjectCanvas, 0, 0);',
    '      shellCtx.globalCompositeOperation = "destination-in";',
    '      shellCtx.drawImage(matteLayer, 0, 0);',
    '      shellCtx.globalCompositeOperation = "source-over";',
    '      if (isClassicLook) {',
    '        ctx.save();',
    '        ctx.globalAlpha = state.effectEnabled ? spec.payload.grade.subjectOpacity : 0.98;',
    '        ctx.globalCompositeOperation = state.effectEnabled ? "multiply" : "source-over";',
    '        ctx.filter = state.effectEnabled',
    '          ? "grayscale(1) saturate(0) brightness(1.18) contrast(1.16)"',
    '          : "grayscale(1) saturate(0) brightness(1.08) contrast(1.04)";',
    '        ctx.drawImage(shellCanvas, 0, 0);',
    '        ctx.restore();',
    '        if (!state.effectEnabled) return;',
    '        glowCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '        glowCtx.fillStyle = spec.payload.grade.rimLightColor;',
    '        glowCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        glowCtx.globalCompositeOperation = "destination-in";',
    '        glowCtx.drawImage(matteLayer, 0, 0);',
    '        glowCtx.globalCompositeOperation = "source-over";',
    '        ctx.save();',
    '        ctx.globalAlpha = spec.payload.grade.rimLightOpacity * reveal;',
    '        ctx.globalCompositeOperation = "screen";',
    '        ctx.filter = "blur(18px)";',
    '        ctx.drawImage(glowCanvas, 0, 0);',
    '        ctx.restore();',
    '        ctx.save();',
    '        ctx.globalAlpha = 0.12 * reveal;',
    '        ctx.globalCompositeOperation = "screen";',
    '        ctx.filter = "blur(4px)";',
    '        ctx.drawImage(shellCanvas, 0, 0);',
    '        ctx.restore();',
    '        return;',
    '      }',
    '      ctx.save();',
    '      ctx.globalAlpha = state.effectEnabled ? spec.payload.grade.subjectOpacity : 0.96;',
    '      ctx.filter = state.effectEnabled',
    '        ? "grayscale(0.12) saturate(0.88) brightness(0.92) contrast(1.06)"',
    '        : "grayscale(0) saturate(1) brightness(1.02) contrast(1.02)";',
    '      ctx.drawImage(shellCanvas, 0, 0);',
    '      ctx.restore();',
    '      if (!state.effectEnabled) return;',
    '      glowCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      glowCtx.fillStyle = spec.payload.grade.rimLightColor;',
    '      glowCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '      glowCtx.globalCompositeOperation = "destination-in";',
    '      glowCtx.drawImage(matteLayer, 0, 0);',
    '      glowCtx.globalCompositeOperation = "source-over";',
    '      ctx.save();',
    '      ctx.globalAlpha = spec.payload.grade.rimLightOpacity * reveal;',
    '      ctx.globalCompositeOperation = "screen";',
    '      ctx.filter = "blur(26px)";',
    '      ctx.drawImage(glowCanvas, 0, 0);',
    '      ctx.restore();',
    '    }',
    '    function drawExposure(elapsedSec, matteLayer, reveal) {',
    '      if (!state.effectEnabled) return;',
    '      const exposureLayout = spec.payload.layout.exposure;',
    '      const motion = spec.payload.animation;',
    '      const drift = easeInOutSine(clamp(elapsedSec / Math.max(spec.durationSec, 0.001), 0, 1));',
    '      const exposureScale = lerp(motion.exposureScaleFrom, motion.exposureScaleTo, drift) * exposureLayout.scale;',
    '      const offsetX = Math.sin(elapsedSec * 0.82) * motion.driftXMaxPx + exposureLayout.offsetXPx;',
    '      const offsetY = Math.cos(elapsedSec * 0.57) * motion.driftYMaxPx + exposureLayout.offsetYPx;',
    '      exposureCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      drawMedia(exposureCtx, exposureNode, {',
    '        fit: spec.payload.exposure.fit,',
    '        scale: exposureScale,',
    '        anchorX: exposureLayout.anchorX,',
    '        anchorY: exposureLayout.anchorY,',
    '        offsetX,',
    '        offsetY,',
    '        alpha: 1,',
    '        filter: isClassicLook',
    '          ? "saturate(0.76) brightness(0.94) contrast(1.12)"',
    '          : "saturate(1.22) brightness(1.02) contrast(1.08)",',
    '      });',
    '      atmosphereNodes.forEach((node, index) => {',
    '        if (!isRenderable(node)) return;',
    '        exposureCtx.save();',
    '        exposureCtx.globalCompositeOperation = "screen";',
    '        exposureCtx.globalAlpha = index === atmosphereNodes.length - 1',
    '          ? (isClassicLook ? spec.payload.grade.lightLeakOpacity * 0.5 : spec.payload.grade.lightLeakOpacity)',
    '          : (isClassicLook ? spec.payload.grade.atmosphereOpacity * 0.5 : spec.payload.grade.atmosphereOpacity);',
    '        drawMedia(exposureCtx, node, { fit: "cover", scale: 1.05, anchorX: 0.5, anchorY: 0.5, alpha: 1 });',
    '        exposureCtx.restore();',
    '      });',
    '      if (isClassicLook) {',
    '        const softnessWash = exposureCtx.createLinearGradient(0, 0, 0, spec.size.h);',
    '        softnessWash.addColorStop(0, "rgba(255,255,255,0.06)");',
    '        softnessWash.addColorStop(0.38, "rgba(255,255,255,0.18)");',
    '        softnessWash.addColorStop(0.7, "rgba(255,255,255,0.1)");',
    '        softnessWash.addColorStop(1, "rgba(255,255,255,0.22)");',
    '        exposureCtx.save();',
    '        exposureCtx.globalCompositeOperation = "screen";',
    '        exposureCtx.fillStyle = softnessWash;',
    '        exposureCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        exposureCtx.restore();',
    '        const faceLift = exposureCtx.createRadialGradient(spec.size.w * 0.76, spec.size.h * 0.36, spec.size.w * 0.03, spec.size.w * 0.76, spec.size.h * 0.36, spec.size.w * 0.24);',
    '        faceLift.addColorStop(0, "rgba(255,255,255,0.18)");',
    '        faceLift.addColorStop(1, "rgba(255,255,255,0)");',
    '        exposureCtx.save();',
    '        exposureCtx.globalCompositeOperation = "screen";',
    '        exposureCtx.fillStyle = faceLift;',
    '        exposureCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        exposureCtx.restore();',
    '      } else {',
    '        const verticalTint = exposureCtx.createLinearGradient(spec.size.w * 0.08, 0, spec.size.w * 0.82, spec.size.h);',
    '        verticalTint.addColorStop(0, `${spec.payload.grade.coolTint}66`);',
    '        verticalTint.addColorStop(0.48, "rgba(244,247,251,0.08)");',
    '        verticalTint.addColorStop(1, `${spec.payload.grade.warmTint}88`);',
    '        exposureCtx.save();',
    '        exposureCtx.globalCompositeOperation = "screen";',
    '        exposureCtx.globalAlpha = 0.26;',
    '        exposureCtx.fillStyle = verticalTint;',
    '        exposureCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        exposureCtx.restore();',
    '      }',
    '      exposureCtx.globalCompositeOperation = "destination-in";',
    '      exposureCtx.drawImage(matteLayer, 0, 0);',
    '      exposureCtx.globalCompositeOperation = "source-over";',
    '      if (isClassicLook) {',
    '        const matteFade = exposureCtx.createLinearGradient(0, 0, 0, spec.size.h);',
    '        matteFade.addColorStop(0, "rgba(255,255,255,0.96)");',
    '        matteFade.addColorStop(0.44, "rgba(255,255,255,0.36)");',
    '        matteFade.addColorStop(0.74, "rgba(255,255,255,0.68)");',
    '        matteFade.addColorStop(1, "rgba(255,255,255,0.92)");',
    '        exposureCtx.save();',
    '        exposureCtx.globalCompositeOperation = "destination-in";',
    '        exposureCtx.fillStyle = matteFade;',
    '        exposureCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '        exposureCtx.restore();',
    '      }',
    '      ctx.save();',
    '      ctx.globalAlpha = spec.payload.grade.exposureOpacity * reveal;',
    '      if (isClassicLook) ctx.globalCompositeOperation = "multiply";',
    '      ctx.drawImage(exposureCanvas, 0, 0);',
    '      ctx.restore();',
    '    }',
    '    function drawAtmosphere(elapsedSec) {',
    '      if (!state.effectEnabled || atmosphereNodes.length === 0) return;',
    '      if (isClassicLook) return;',
    '      atmosphereNodes.forEach((node, index) => {',
    '        if (!isRenderable(node)) return;',
    '        ctx.save();',
    '        ctx.globalCompositeOperation = "screen";',
    '        ctx.globalAlpha = index === atmosphereNodes.length - 1',
    '          ? spec.payload.grade.lightLeakOpacity * 0.82',
    '          : spec.payload.grade.atmosphereOpacity * 0.9;',
    '        drawMedia(ctx, node, {',
    '          fit: "cover",',
    '          scale: 1.06,',
    '          anchorX: 0.5,',
    '          anchorY: 0.5,',
    '          offsetX: Math.sin(elapsedSec * 0.31) * 18,',
    '          offsetY: Math.cos(elapsedSec * 0.24) * 14,',
    '          alpha: 1,',
    '        });',
    '        ctx.restore();',
    '      });',
    '    }',
    '    function drawVignette() {',
    '      const vignette = ctx.createRadialGradient(spec.size.w * 0.56, spec.size.h * 0.48, spec.size.w * 0.08, spec.size.w * 0.56, spec.size.h * 0.48, spec.size.w * 0.78);',
    '      vignette.addColorStop(0, isClassicLook ? "rgba(255,255,255,0)" : "rgba(5,8,19,0)");',
    '      vignette.addColorStop(1, isClassicLook ? `rgba(242,237,231,${spec.payload.grade.vignetteOpacity})` : `rgba(5,8,19,${spec.payload.grade.vignetteOpacity})`);',
    '      ctx.fillStyle = vignette;',
    '      ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '    }',
    '    function drawClassicMist(matteLayer, elapsedSec) {',
    '      if (!isClassicLook || !state.effectEnabled) return;',
    '      glowCtx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      const innerMist = glowCtx.createLinearGradient(0, spec.size.h * 0.44, 0, spec.size.h);',
    '      innerMist.addColorStop(0, "rgba(255,255,255,0)");',
    '      innerMist.addColorStop(0.6, "rgba(255,255,255,0.36)");',
    '      innerMist.addColorStop(1, "rgba(255,255,255,0.72)");',
    '      glowCtx.fillStyle = innerMist;',
    '      glowCtx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '      glowCtx.globalCompositeOperation = "destination-in";',
    '      glowCtx.drawImage(matteLayer, 0, 0);',
    '      glowCtx.globalCompositeOperation = "source-over";',
    '      ctx.save();',
    '      ctx.globalAlpha = 0.58;',
    '      ctx.globalCompositeOperation = "screen";',
    '      ctx.filter = "blur(26px)";',
    '      ctx.drawImage(glowCanvas, 0, 0);',
    '      ctx.restore();',
    '      const lowerFog = ctx.createLinearGradient(0, spec.size.h * 0.6, 0, spec.size.h);',
    '      lowerFog.addColorStop(0, "rgba(255,255,255,0)");',
    '      lowerFog.addColorStop(1, "rgba(255,255,255,0.42)");',
    '      ctx.save();',
    '      ctx.globalAlpha = 0.65 + Math.sin(elapsedSec * 0.45) * 0.04;',
    '      ctx.fillStyle = lowerFog;',
    '      ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '      ctx.restore();',
    '    }',
    '    function setEffectEnabled(enabled) {',
    '      state.effectEnabled = enabled;',
    '      root.classList.toggle("de-effect-disabled", !enabled);',
    '      if (compareToggle) {',
    '        compareToggle.textContent = enabled ? "Effect On" : "Effect Off";',
    '        compareToggle.setAttribute("aria-pressed", enabled ? "true" : "false");',
    '      }',
    '    }',
    '    function drawFrame(now) {',
    '      if (!state.started) return;',
    '      const elapsed = motionEnabled ? ((now - state.previewStart) / 1000) % spec.durationSec : spec.payload.animation.introDurationSec;',
    '      const motion = spec.payload.animation;',
    '      const intro = motion.introDurationSec > 0 ? clamp(elapsed / motion.introDurationSec, 0, 1) : 1;',
    '      const outroStart = Math.max(0, spec.durationSec - motion.outroDurationSec);',
    '      const outro = motion.outroDurationSec > 0 ? clamp((elapsed - outroStart) / motion.outroDurationSec, 0, 1) : 0;',
    '      const reveal = easeOutCubic(intro) * (outro > 0 ? 1 - easeInCubic(outro) : 1);',
    '      state.subjectFloatY = Math.sin(elapsed * 0.74) * motion.subjectFloatYPx;',
    '      ctx.clearRect(0, 0, spec.size.w, spec.size.h);',
    '      ctx.fillStyle = spec.payload.grade.backgroundFill;',
    '      ctx.fillRect(0, 0, spec.size.w, spec.size.h);',
    '      drawBackground(elapsed);',
    '      const matteLayer = buildMatte();',
    '      if (isClassicLook) {',
    '        drawExposure(elapsed, matteLayer, reveal);',
    '        drawSubjectShell(matteLayer, reveal);',
    '        drawClassicMist(matteLayer, elapsed);',
    '      } else {',
    '        drawSubjectShell(matteLayer, reveal);',
    '        drawExposure(elapsed, matteLayer, reveal);',
    '      }',
    '      drawAtmosphere(elapsed);',
    '      drawVignette();',
    '      requestAnimationFrame(drawFrame);',
    '    }',
    '    function maybeStart() {',
    '      const ready = [subjectNode, exposureNode, backgroundNode, ...atmosphereNodes].every((node) => !node || isRenderable(node));',
    '      if (!ready || state.started) return;',
    '      resizeCanvases();',
    '      state.started = true;',
    '      state.previewStart = performance.now();',
    '      [subjectNode, exposureNode, backgroundNode, ...atmosphereNodes].forEach((node) => {',
    '        if (node && node.tagName === "VIDEO" && motionEnabled) {',
    '          node.play().catch(() => {});',
    '        }',
    '      });',
    '      requestAnimationFrame(drawFrame);',
    '    }',
    '    [subjectNode, exposureNode, backgroundNode, ...atmosphereNodes].forEach((node) => {',
    '      if (!node) return;',
    '      if (node.tagName === "VIDEO") {',
    '        node.addEventListener("loadeddata", maybeStart, { once: true });',
    '      } else if (node.complete) {',
    '        queueMicrotask(maybeStart);',
    '      } else {',
    '        node.addEventListener("load", maybeStart, { once: true });',
    '      }',
    '    });',
    '    maybeStart();',
    '    if (spec.payload.preview.allowEffectToggle && compareToggle) {',
    '      compareToggle.addEventListener("click", () => setEffectEnabled(!state.effectEnabled));',
    '      window.addEventListener("keydown", (event) => {',
    '        if (event.key.toLowerCase() === "d") setEffectEnabled(!state.effectEnabled);',
    '      });',
    '    }',
    `    setEffectEnabled(${payload.preview.effectInitiallyEnabled ? 'true' : 'false'});`,
    '    const tl = gsap.timeline({ paused: true });',
    '    window.__timelines = window.__timelines || {};',
    `    window.__timelines["${escapeAttribute(compositionId)}"] = tl;`,
    '  </script>',
    '</body>',
    '</html>',
  ].join('\n');
}

export function buildHyperframesDoubleExposureComposition(
  input: DoubleExposureSceneInput
) {
  return renderHyperframesDoubleExposureComposition(
    createDoubleExposureSceneSpec(input)
  );
}
