import {
  createTextMaskSceneSpec,
  type TextMaskSceneInput,
  type TextMaskSceneSpec,
} from '@/lib/video/textMask';

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeAttribute(value: string) {
  return escapeHtml(value).replaceAll("'", '&#39;');
}

function renderMediaTag(
  kind: 'video' | 'image',
  attrs: Record<string, string | undefined>,
  extraClassName?: string
) {
  const renderedAttrs = Object.entries({
    ...attrs,
    ...(extraClassName ? { class: extraClassName } : {}),
  })
    .filter((entry): entry is [string, string] => entry[1] !== undefined)
    .map(([key, value]) => `${key}="${escapeAttribute(value)}"`)
    .join(' ');

  if (kind === 'video') {
    return `<video ${renderedAttrs}></video>`;
  }

  return `<img ${renderedAttrs} />`;
}

export function renderHyperframesTextMaskComposition(spec: TextMaskSceneSpec) {
  const preview = spec.payload.preview;
  const motion = spec.payload.motion;
  const background = spec.payload.background;
  const settledBackgroundScale = Math.max(1, motion.mediaScaleTo + 0.04);
  const settledMaskScale = motion.mediaScaleTo;
  const mediaAttrs =
    spec.payload.media.kind === 'video'
      ? {
          src: spec.payload.media.url,
          ...(spec.payload.media.posterUrl ? { poster: spec.payload.media.posterUrl } : {}),
          playsinline: 'true',
          muted: 'true',
          autoplay: preview.motionEnabled ? 'true' : undefined,
          loop: preview.motionEnabled ? 'true' : undefined,
          preload: 'auto',
        }
      : {
          src: spec.payload.media.url,
          loading: 'eager',
          decoding: 'sync',
        };
  const audio = spec.payload.audio;
  const audioAttrs = audio
    ? {
        id: 'hf-audio',
        src: audio.url,
        'data-start': '0',
        'data-duration': String(spec.durationSec),
        'data-track-index': '2',
        'data-volume': String(audio.volume),
        preload: 'auto',
      }
    : null;

  const compositionId = spec.payload.id;
  const previewTitle = spec.payload.lines.join(' ');
  const maskDataUrl = spec.payload.maskDataUrl;
  const overlay = spec.payload.overlay;
  const rootClasses = ['hf-root', !preview.maskInitiallyEnabled ? 'hf-mask-disabled' : '']
    .filter(Boolean)
    .join(' ');
  const toggleButtonLabel = preview.maskInitiallyEnabled ? 'Mask On' : 'Mask Off';

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width,initial-scale=1" />',
    `  <title>${escapeHtml(spec.title ?? 'Text Mask Intro')}</title>`,
    '  <style>',
    '    html, body { margin: 0; width: 100%; height: 100%; background: #050813; }',
    '    body { overflow: hidden; }',
    '    #root { position: relative; width: 100%; height: 100%; }',
    `    [data-composition-id="${escapeAttribute(compositionId)}"] {`,
    '      position: relative;',
    '      width: 100%;',
    '      height: 100%;',
    `      background: ${background.fill};`,
    '      overflow: hidden;',
    '      isolation: isolate;',
    `      --hf-copy-opacity: ${preview.motionEnabled ? 0 : 1};`,
    `      --hf-copy-y: ${preview.motionEnabled ? `${motion.textOffsetYPx}px` : '0px'};`,
    `      --hf-copy-blur: ${preview.motionEnabled ? '18px' : '0px'};`,
    `      --hf-bg-scale: ${preview.motionEnabled ? background.scale : settledBackgroundScale};`,
    '      --hf-bg-x: 0px;',
    '      --hf-bg-y: 0px;',
    `      --hf-mask-scale: ${preview.motionEnabled ? motion.mediaScaleFrom : settledMaskScale};`,
    '      --hf-mask-x: 0px;',
    '      --hf-mask-y: 0px;',
    `      --hf-support-opacity: ${preview.motionEnabled ? 0 : 1};`,
    '    }',
    '    .hf-stage, .hf-layer { position: absolute; inset: 0; }',
    '    .hf-stage { background: radial-gradient(circle at 50% 44%, rgba(12, 20, 58, 0.18), rgba(5, 8, 19, 0.92) 74%); }',
    '    .hf-media { width: 100%; height: 100%; object-fit: cover; object-position: center center; display: block; }',
    '    .hf-plain-media { opacity: 0; filter: none; transform: none; transition: opacity 160ms ease; }',
    '    .hf-bg-media {',
    `      opacity: ${Math.max(0.12, 1 - background.dimOpacity).toFixed(3)};`,
    `      filter: blur(${Math.max(18, background.blurPx)}px) saturate(0.82) brightness(0.34) contrast(1.06);`,
      '      transform: translate3d(var(--hf-bg-x), var(--hf-bg-y), 0) scale(var(--hf-bg-scale));',
    '      transform-origin: center center;',
    '    }',
    '    .hf-grade {',
    '      background:',
    '        radial-gradient(circle at 26% 24%, rgba(99, 214, 255, 0.16), transparent 28%),',
    '        radial-gradient(circle at 74% 68%, rgba(255, 122, 26, 0.18), transparent 34%),',
    '        linear-gradient(180deg, rgba(5, 8, 19, 0.16), rgba(5, 8, 19, 0.78));',
    '      mix-blend-mode: screen;',
    '      pointer-events: none;',
    '    }',
    '    .hf-vignette {',
    '      background: radial-gradient(circle at 50% 50%, rgba(5, 8, 19, 0), rgba(5, 8, 19, 0.76) 78%);',
    '      pointer-events: none;',
    '    }',
    '    .hf-grain {',
    '      opacity: 0.08;',
    '      background-image:',
    '        radial-gradient(circle at 18% 16%, rgba(255,255,255,0.65) 0.6px, transparent 0.7px),',
    '        radial-gradient(circle at 72% 68%, rgba(255,255,255,0.35) 0.6px, transparent 0.8px);',
    '      background-size: 7px 7px, 9px 9px;',
    '      mix-blend-mode: soft-light;',
    '      pointer-events: none;',
    '    }',
    '    .hf-letterbox::before, .hf-letterbox::after {',
    '      content: "";',
    '      position: absolute;',
    '      left: 0;',
    '      right: 0;',
    '      height: 58px;',
    '      background: rgba(2, 4, 10, 0.9);',
    '      z-index: 8;',
    '      pointer-events: none;',
    '    }',
    '    .hf-letterbox::before { top: 0; box-shadow: 0 20px 48px rgba(2, 4, 10, 0.42); }',
    '    .hf-letterbox::after { bottom: 0; box-shadow: 0 -20px 48px rgba(2, 4, 10, 0.42); }',
    '    .hf-mask-shell {',
    `      -webkit-mask-image: url("${maskDataUrl}");`,
    `      mask-image: url("${maskDataUrl}");`,
    '      -webkit-mask-repeat: no-repeat;',
    '      mask-repeat: no-repeat;',
    '      -webkit-mask-size: 100% 100%;',
    '      mask-size: 100% 100%;',
    '      -webkit-mask-position: center center;',
    '      mask-position: center center;',
    '      -webkit-mask-mode: alpha;',
    '      mask-mode: alpha;',
    '      transform: translate3d(0, var(--hf-copy-y), 0);',
    '      transform-origin: center center;',
    '      opacity: var(--hf-copy-opacity);',
    '      pointer-events: none;',
    '    }',
    '    .hf-mask-shadow {',
    '      background: rgba(2, 4, 10, 0.58);',
    '      filter: blur(12px);',
    '      transform: translate3d(0, calc(var(--hf-copy-y) + 10px), 0) scale(1.004);',
    '      opacity: calc(var(--hf-copy-opacity) * 0.44);',
    '    }',
    '    .hf-mask-glow {',
    '      mix-blend-mode: screen;',
    '      filter: blur(12px);',
    '      opacity: calc(var(--hf-copy-opacity) * 0.36);',
    '    }',
    '    .hf-mask-glow .hf-media {',
    '      transform: translate3d(var(--hf-mask-x), var(--hf-mask-y), 0) scale(calc(var(--hf-mask-scale) + 0.04));',
    '      transform-origin: center center;',
    '      filter: saturate(1.18) brightness(1.02) contrast(1.08);',
    '    }',
    '    .hf-mask-tint {',
    '      background:',
    '        linear-gradient(110deg, rgba(99, 214, 255, 0.42) 0%, rgba(244, 247, 251, 0.08) 42%, rgba(255, 122, 26, 0.54) 100%);',
    '      mix-blend-mode: soft-light;',
    '      opacity: calc(var(--hf-copy-opacity) * 0.18);',
    '    }',
    '    .hf-mask-fill {',
    '      opacity: var(--hf-copy-opacity);',
    '    }',
    '    .hf-mask-fill .hf-media {',
    '      transform: translate3d(var(--hf-mask-x), var(--hf-mask-y), 0) scale(var(--hf-mask-scale));',
    '      transform-origin: center center;',
    '      filter: saturate(1.06) brightness(1.02) contrast(1.06);',
    '    }',
    '    .hf-mask-toggle {',
    '      position: absolute;',
    '      top: 84px;',
    '      right: 118px;',
    '      z-index: 12;',
    '      border: 1px solid rgba(244,247,251,0.18);',
    '      background: rgba(7, 10, 20, 0.76);',
    '      color: rgba(244,247,251,0.92);',
    '      border-radius: 999px;',
    '      padding: 12px 18px;',
    '      font: 600 13px/1 "Helvetica Neue", Arial, sans-serif;',
    '      letter-spacing: 0.12em;',
    '      text-transform: uppercase;',
    '      cursor: pointer;',
    '      backdrop-filter: blur(10px);',
    '      transition: background 140ms ease, border-color 140ms ease, opacity 140ms ease;',
    '    }',
    '    .hf-mask-toggle:hover { background: rgba(14, 18, 34, 0.9); border-color: rgba(244,247,251,0.32); }',
    '    .hf-mask-toggle[hidden] { display: none; }',
    '    .hf-mask-disabled .hf-mask-shell { opacity: 0 !important; }',
    '    .hf-mask-disabled .hf-bg-media { opacity: 0; }',
    '    .hf-mask-disabled .hf-plain-media { opacity: 1; }',
    '    .hf-mask-disabled .hf-grade, .hf-mask-disabled .hf-vignette, .hf-mask-disabled .hf-grain, .hf-mask-disabled .hf-letterbox { opacity: 0; }',
    '    .hf-copy-chrome {',
    '      position: absolute;',
    '      left: 118px;',
    '      right: 118px;',
    '      pointer-events: none;',
    '      z-index: 7;',
    '      color: rgba(244, 247, 251, 0.9);',
    '      font-family: "Helvetica Neue", Arial, sans-serif;',
    '    }',
    '    .hf-kicker {',
    '      top: 96px;',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 18px;',
    '      font-size: 24px;',
    '      font-weight: 600;',
    '      letter-spacing: 0.18em;',
    '      text-transform: uppercase;',
    '      opacity: calc(0.24 + var(--hf-support-opacity) * 0.62);',
    '      transform: translate3d(0, calc(var(--hf-copy-y) * 0.45), 0);',
    '    }',
    '    .hf-kicker::before {',
    '      content: "";',
    '      width: 84px;',
    '      height: 1px;',
    '      background: linear-gradient(90deg, rgba(244,247,251,0.88), rgba(244,247,251,0));',
    '    }',
    '    .hf-footer {',
    '      bottom: 92px;',
    '      max-width: 640px;',
    '      font-size: 20px;',
    '      line-height: 1.4;',
    '      letter-spacing: 0.02em;',
    '      opacity: calc(0.16 + var(--hf-support-opacity) * 0.54);',
    '      transform: translate3d(0, calc(var(--hf-copy-y) * 0.24), 0);',
    '    }',
    '    .hf-footer strong { display: block; margin-bottom: 8px; font-size: 15px; letter-spacing: 0.2em; text-transform: uppercase; }',
    '    .hf-accessibility { position: absolute; width: 1px; height: 1px; padding: 0; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }',
    '    @media (max-width: 1100px) {',
    '      .hf-copy-chrome { left: 56px; right: 56px; }',
    '      .hf-mask-toggle { top: 62px; right: 56px; padding: 10px 14px; font-size: 11px; }',
    '      .hf-kicker { top: 74px; font-size: 18px; gap: 12px; }',
    '      .hf-kicker::before { width: 56px; }',
      '      .hf-footer { bottom: 72px; font-size: 16px; max-width: 460px; }',
    '      .hf-letterbox::before, .hf-letterbox::after { height: 36px; }',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    `  <div id="root" class="${escapeAttribute(rootClasses)}" data-composition-id="${escapeAttribute(compositionId)}" data-start="0" data-duration="${spec.durationSec}" data-width="${spec.size.w}" data-height="${spec.size.h}">`,
    '    <div class="hf-stage">',
    '      <div class="hf-layer">',
    `        ${renderMediaTag(spec.payload.media.kind, mediaAttrs, 'hf-media hf-bg-media hf-autoplay')}`,
    '      </div>',
    '      <div class="hf-layer">',
    `        ${renderMediaTag(spec.payload.media.kind, mediaAttrs, 'hf-media hf-plain-media hf-autoplay')}`,
    '      </div>',
    '      <div class="hf-layer hf-grade"></div>',
    '      <div class="hf-layer hf-mask-shadow hf-mask-shell"></div>',
    '      <div class="hf-layer hf-mask-glow hf-mask-shell">',
    `        ${renderMediaTag(spec.payload.media.kind, mediaAttrs, 'hf-media hf-autoplay')}`,
    '      </div>',
    '      <div class="hf-layer hf-mask-tint hf-mask-shell"></div>',
    '      <div class="hf-layer hf-mask-fill hf-mask-shell">',
    `        ${renderMediaTag(spec.payload.media.kind, mediaAttrs, 'hf-media hf-autoplay')}`,
    '      </div>',
    '      <div class="hf-layer hf-vignette"></div>',
    '      <div class="hf-layer hf-grain"></div>',
    audioAttrs ? `      <audio ${Object.entries(audioAttrs).map(([key, value]) => `${key}="${escapeAttribute(value)}"`).join(' ')}></audio>` : '',
    `      <button type="button" id="hf-mask-toggle" class="hf-mask-toggle"${preview.allowMaskToggle ? '' : ' hidden'}>${escapeHtml(toggleButtonLabel)}</button>`,
    `      <div class="hf-copy-chrome hf-kicker">${escapeHtml(overlay.kicker)}</div>`,
    `      <div class="hf-copy-chrome hf-footer"><strong>${escapeHtml(overlay.footerTitle)}</strong>${escapeHtml(overlay.footerBody)}</div>`,
    `      <div class="hf-accessibility">${escapeHtml(previewTitle)}</div>`,
    '      <div class="hf-layer hf-letterbox"></div>',
    '    </div>',
    '  </div>',
    '  <script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js"></script>',
    '  <script>',
    '    const root = document.querySelector("[data-composition-id]");',
    '    const maskToggle = document.getElementById("hf-mask-toggle");',
    `    const motionEnabled = ${preview.motionEnabled ? 'true' : 'false'};`,
    `    const allowMaskToggle = ${preview.allowMaskToggle ? 'true' : 'false'};`,
    `    const durationSec = ${spec.durationSec};`,
    `    const introDurationSec = ${motion.introDurationSec};`,
    `    const outroDurationSec = ${motion.outroDurationSec};`,
    `    const baseTextOffset = ${motion.textOffsetYPx};`,
    `    const backgroundScaleFrom = ${background.scale};`,
    `    const backgroundScaleTo = ${settledBackgroundScale};`,
    `    const maskScaleFrom = ${motion.mediaScaleFrom};`,
    `    const maskScaleTo = ${settledMaskScale};`,
    '    function clamp(value, min, max) { return Math.min(max, Math.max(min, value)); }',
    '    function lerp(a, b, t) { return a + (b - a) * t; }',
    '    function easeOutCubic(t) { return 1 - Math.pow(1 - t, 3); }',
    '    function easeInCubic(t) { return t * t * t; }',
    '    function easeInOutSine(t) { return -(Math.cos(Math.PI * t) - 1) / 2; }',
    '    function setVar(name, value) { root.style.setProperty(name, value); }',
    '    function setMaskEnabled(enabled) {',
    '      root.classList.toggle("hf-mask-disabled", !enabled);',
    '      if (maskToggle) {',
    '        maskToggle.textContent = enabled ? "Mask On" : "Mask Off";',
    '        maskToggle.setAttribute("aria-pressed", enabled ? "true" : "false");',
    '      }',
    '    }',
    '    function setStaticPreview() {',
    '      setVar("--hf-copy-opacity", "1");',
    '      setVar("--hf-support-opacity", "1");',
    '      setVar("--hf-copy-y", "0px");',
    '      setVar("--hf-copy-blur", "0px");',
    '      setVar("--hf-bg-scale", backgroundScaleTo.toFixed(4));',
    '      setVar("--hf-bg-x", "0px");',
    '      setVar("--hf-bg-y", "0px");',
    '      setVar("--hf-mask-scale", maskScaleTo.toFixed(4));',
    '      setVar("--hf-mask-x", "0px");',
    '      setVar("--hf-mask-y", "0px");',
    '    }',
    '    function syncPreview(now) {',
    '      const elapsed = (now - previewStart) / 1000;',
    '      const t = durationSec > 0 ? elapsed % durationSec : 0;',
    '      const intro = introDurationSec > 0 ? clamp(t / introDurationSec, 0, 1) : 1;',
    '      const outroStart = Math.max(0, durationSec - outroDurationSec);',
    '      const outro = outroDurationSec > 0 ? clamp((t - outroStart) / outroDurationSec, 0, 1) : 0;',
    '      const reveal = easeOutCubic(intro) * (outro > 0 ? 1 - easeInCubic(outro) : 1);',
    '      const drift = easeInOutSine(clamp(t / Math.max(durationSec, 0.001), 0, 1));',
    '      const bgX = Math.sin(t * 0.72) * 26;',
    '      const bgY = Math.cos(t * 0.51) * 18;',
    '      const maskX = Math.sin(t * 0.54) * 74;',
    '      const maskY = Math.cos(t * 0.37) * 34;',
    '      setVar("--hf-copy-opacity", reveal.toFixed(4));',
    '      setVar("--hf-support-opacity", clamp((reveal - 0.18) / 0.82, 0, 1).toFixed(4));',
    '      setVar("--hf-copy-y", `${lerp(baseTextOffset, 0, easeOutCubic(intro)).toFixed(2)}px`);',
    '      setVar("--hf-copy-blur", `${lerp(18, 0, easeOutCubic(intro)).toFixed(2)}px`);',
    '      setVar("--hf-bg-scale", lerp(backgroundScaleFrom, backgroundScaleTo, drift).toFixed(4));',
    '      setVar("--hf-bg-x", `${bgX.toFixed(2)}px`);',
    '      setVar("--hf-bg-y", `${bgY.toFixed(2)}px`);',
    '      setVar("--hf-mask-scale", lerp(maskScaleFrom, maskScaleTo, drift).toFixed(4));',
    '      setVar("--hf-mask-x", `${maskX.toFixed(2)}px`);',
    '      setVar("--hf-mask-y", `${maskY.toFixed(2)}px`);',
    '      requestAnimationFrame(syncPreview);',
    '    }',
    '    const previewStart = performance.now();',
    '    document.querySelectorAll(".hf-autoplay").forEach((element) => {',
    '      if (element.tagName === "VIDEO" && motionEnabled) {',
    '        const video = element;',
    '        const attemptPlay = () => video.play().catch(() => {});',
    '        if (video.readyState >= 2) attemptPlay();',
    '        else video.addEventListener("loadeddata", attemptPlay, { once: true });',
    '      }',
    '    });',
    '    if (allowMaskToggle && maskToggle) {',
    '      maskToggle.addEventListener("click", () => {',
    '        setMaskEnabled(root.classList.contains("hf-mask-disabled"));',
    '      });',
    '      window.addEventListener("keydown", (event) => {',
    '        if (event.key.toLowerCase() === "m") setMaskEnabled(root.classList.contains("hf-mask-disabled"));',
    '      });',
    '    }',
    '    if (motionEnabled) requestAnimationFrame(syncPreview);',
    '    else setStaticPreview();',
    `    setMaskEnabled(${preview.maskInitiallyEnabled ? 'true' : 'false'});`,
    '    const tl = gsap.timeline({ paused: true });',
    '    window.__timelines = window.__timelines || {};',
    `    window.__timelines["${escapeAttribute(compositionId)}"] = tl;`,
    '  </script>',
    '</body>',
    '</html>',
  ].join('\n');
}

export function buildHyperframesTextMaskComposition(input: TextMaskSceneInput) {
  return renderHyperframesTextMaskComposition(createTextMaskSceneSpec(input));
}
