/**
 * persistManifest.ts — AC5 step 2: write a drafted SKILL.md to disk.
 *
 * After a creator accepts a draft manifest, the manifest is materialised at
 * `lib/agent/skills/<name>/SKILL.md` so subsequent `callSkill` invocations can
 * load it. Reference files are not yet generated by the drafter — when they
 * are, this helper will gain a sibling `persistReferenceFile` writer.
 *
 * Path resolution:
 *   - `repoRoot` defaults to `process.cwd()` (the Next.js server's working
 *     directory). Pass it explicitly in tests pointing at a temp dir.
 *   - The skill directory is `<repoRoot>/lib/agent/skills/<sanitisedId>`.
 *   - The id is sanitised to kebab-case before joining; we never accept paths
 *     with `..` or path separators (defence in depth — the drafter already
 *     emits kebab-case but creators can override).
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import type { SkillManifest, SkillRef } from './types';

export interface PersistDraftSkillOptions {
  manifest: SkillManifest;
  /** Defaults to `process.cwd()`. Override in tests. */
  repoRoot?: string;
  /**
   * When true, throw if a SKILL.md already exists at the target path. Defaults
   * to true (we never want to silently overwrite a previously-pinned skill).
   */
  failIfExists?: boolean;
}

export interface PersistDraftSkillResult {
  skillDir: string;
  manifestPath: string;
  skillRef: SkillRef;
}

const SAFE_ID_RE = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;

function assertSafeId(id: string): void {
  if (!SAFE_ID_RE.test(id)) {
    throw new Error(
      `[persistDraftSkill] unsafe skill id "${id}" — must be kebab-case [a-z0-9-]+`
    );
  }
}

/**
 * Render a SkillManifest back into the on-disk SKILL.md format.
 * Front-matter uses block-sequence arrays for parity with the existing
 * `brand-ingest/SKILL.md`.
 */
export function renderManifestToMarkdown(manifest: SkillManifest): string {
  const fmLines: string[] = ['---', `name: ${manifest.name}`, `version: ${manifest.version}`];
  fmLines.push(`description: ${manifest.description}`);
  if (manifest.tools.length > 0) {
    fmLines.push('tools:');
    for (const tool of manifest.tools) fmLines.push(`  - ${tool}`);
  } else {
    fmLines.push('tools: []');
  }
  if (manifest.referenceFiles.length > 0) {
    fmLines.push('referenceFiles:');
    for (const ref of manifest.referenceFiles) fmLines.push(`  - ${ref}`);
  } else {
    fmLines.push('referenceFiles: []');
  }
  fmLines.push('---', '', manifest.instructions.trimEnd(), '');
  return fmLines.join('\n');
}

export async function persistDraftSkill(
  opts: PersistDraftSkillOptions
): Promise<PersistDraftSkillResult> {
  const { manifest, failIfExists = true } = opts;
  assertSafeId(manifest.name);
  const repoRoot = opts.repoRoot ?? process.cwd();
  const skillDir = path.join(repoRoot, 'lib', 'agent', 'skills', manifest.name);
  const manifestPath = path.join(skillDir, 'SKILL.md');

  if (failIfExists) {
    try {
      await fs.access(manifestPath);
      throw new Error(
        `[persistDraftSkill] a skill named "${manifest.name}" already exists at ${manifestPath}`
      );
    } catch (err) {
      // ENOENT is the desired path. Re-throw any other error (including the
      // explicit "already exists" we just threw above).
      const message = err instanceof Error ? err.message : String(err);
      if (!/ENOENT/i.test(message) && !/no such file/i.test(message)) throw err;
    }
  }

  await fs.mkdir(skillDir, { recursive: true });
  const contents = renderManifestToMarkdown(manifest);
  await fs.writeFile(manifestPath, contents, 'utf-8');

  const skillRef: SkillRef = {
    kind: 'skill',
    id: manifest.name,
    version: manifest.version,
    manifestPath,
    manifest,
  };
  return { skillDir, manifestPath, skillRef };
}
