#!/usr/bin/env bash
# deploy.sh — provision Cloud SQL + Upstash Redis, write secrets, deploy Postiz to Cloud Run.
#
# Prerequisites:
#   1. gcloud CLI authenticated: gcloud auth login && gcloud auth application-default login
#   2. .env.postiz populated from .env.postiz.example in this directory
#
# Usage:
#   cp infra/postiz/.env.postiz.example infra/postiz/.env.postiz
#   # fill in .env.postiz
#   bash infra/postiz/deploy.sh [--dry-run]
#
# Pass --dry-run to print every gcloud command without executing it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.postiz"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: ${ENV_FILE} not found. Copy .env.postiz.example and fill it in." >&2
  exit 1
fi

# shellcheck source=/dev/null
source "${ENV_FILE}"

DRY_RUN=false
for arg in "$@"; do
  if [[ "${arg}" == "--dry-run" ]]; then
    DRY_RUN=true
  fi
done

run() {
  if "${DRY_RUN}"; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

# ── Validate required vars ─────────────────────────────────────────────────────
# DATABASE_URL is generated by this script (see "Provision SQL user" below).
required_vars=(
  GCLOUD_PROJECT GCLOUD_REGION CLOUD_RUN_SERVICE CLOUD_RUN_IMAGE
  REDIS_URL JWT_SECRET
)
for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: ${var} is not set in ${ENV_FILE}" >&2
    exit 1
  fi
done

echo "==> Project: ${GCLOUD_PROJECT}  Region: ${GCLOUD_REGION}"

# ── Set active project ─────────────────────────────────────────────────────────
run gcloud config set project "${GCLOUD_PROJECT}"

# ── Enable required APIs ───────────────────────────────────────────────────────
run gcloud services enable \
  run.googleapis.com \
  sqladmin.googleapis.com \
  secretmanager.googleapis.com \
  cloudbuild.googleapis.com \
  --project="${GCLOUD_PROJECT}"

# ── Create Cloud SQL Postgres instance (idempotent — fails gracefully if exists) ──
echo "==> Creating Cloud SQL instance postiz-pg (skip if already exists) ..."
run gcloud sql instances create postiz-pg \
  --database-version=POSTGRES_16 \
  --tier=db-f1-micro \
  --region="${GCLOUD_REGION}" \
  --project="${GCLOUD_PROJECT}" \
  --quiet 2>/dev/null || echo "    (already exists, continuing)"

run gcloud sql databases create postiz \
  --instance=postiz-pg \
  --project="${GCLOUD_PROJECT}" \
  --quiet 2>/dev/null || echo "    (db already exists, continuing)"

# ── Provision SQL user + construct DATABASE_URL ────────────────────────────────
# We generate the password ourselves and immediately bake it into DATABASE_URL
# so the value pushed to Secret Manager always matches the live SQL user. The
# user never has to touch DATABASE_URL — that's why .env.postiz.example does
# not list it. Re-runs rotate the password (idempotent via set-password).
echo "==> Provisioning Cloud SQL user postiz + setting password ..."
if "${DRY_RUN}"; then
  DB_PASSWORD="<dry-run-placeholder>"
  echo "[dry-run] generate DB_PASSWORD via openssl rand -hex 16"
  echo "[dry-run] gcloud sql users create-or-set-password postiz with generated value"
else
  DB_PASSWORD="$(openssl rand -hex 16)"
  if gcloud sql users describe postiz --instance=postiz-pg --project="${GCLOUD_PROJECT}" --quiet 2>/dev/null >/dev/null; then
    gcloud sql users set-password postiz \
      --instance=postiz-pg \
      --password="${DB_PASSWORD}" \
      --project="${GCLOUD_PROJECT}" \
      --quiet
    echo "    (rotated password on existing user)"
  else
    gcloud sql users create postiz \
      --instance=postiz-pg \
      --password="${DB_PASSWORD}" \
      --project="${GCLOUD_PROJECT}" \
      --quiet
    echo "    (created user)"
  fi
fi

DATABASE_URL="postgresql://postiz:${DB_PASSWORD}@/postiz?host=/cloudsql/${GCLOUD_PROJECT}:${GCLOUD_REGION}:postiz-pg"

# ── Create service account for Cloud Run ──────────────────────────────────────
SA_EMAIL="postiz-runner@${GCLOUD_PROJECT}.iam.gserviceaccount.com"
run gcloud iam service-accounts create postiz-runner \
  --display-name="Postiz Cloud Run runner" \
  --project="${GCLOUD_PROJECT}" \
  --quiet 2>/dev/null || echo "    (SA already exists, continuing)"

run gcloud projects add-iam-policy-binding "${GCLOUD_PROJECT}" \
  --member="serviceAccount:${SA_EMAIL}" \
  --role=roles/cloudsql.client \
  --quiet

run gcloud projects add-iam-policy-binding "${GCLOUD_PROJECT}" \
  --member="serviceAccount:${SA_EMAIL}" \
  --role=roles/secretmanager.secretAccessor \
  --quiet

# ── Push secrets to Secret Manager ───────────────────────────────────────────
push_secret() {
  local name="$1"
  local value="$2"
  if "${DRY_RUN}"; then
    echo "[dry-run] push secret ${name}"
    return
  fi
  # Create if missing, then add a new version.
  gcloud secrets describe "${name}" --project="${GCLOUD_PROJECT}" --quiet 2>/dev/null \
    || gcloud secrets create "${name}" --replication-policy=automatic --project="${GCLOUD_PROJECT}" --quiet
  printf '%s' "${value}" \
    | gcloud secrets versions add "${name}" --data-file=- --project="${GCLOUD_PROJECT}" --quiet
  # Grant SA access.
  gcloud secrets add-iam-policy-binding "${name}" \
    --member="serviceAccount:${SA_EMAIL}" \
    --role=roles/secretmanager.secretAccessor \
    --project="${GCLOUD_PROJECT}" \
    --quiet
}

push_secret "postiz-database-url"            "${DATABASE_URL}"
push_secret "postiz-redis-url"               "${REDIS_URL}"
push_secret "postiz-jwt-secret"              "${JWT_SECRET}"
push_secret "postiz-backend-url"             "${BACKEND_INTERNAL_URL:-placeholder}"
push_secret "postiz-instagram-client-id"     "${INSTAGRAM_CLIENT_ID:-}"
push_secret "postiz-instagram-client-secret" "${INSTAGRAM_CLIENT_SECRET:-}"
push_secret "postiz-facebook-client-id"      "${FACEBOOK_CLIENT_ID:-}"
push_secret "postiz-facebook-client-secret"  "${FACEBOOK_CLIENT_SECRET:-}"
push_secret "postiz-x-client-id"             "${X_CLIENT_ID:-}"
push_secret "postiz-x-client-secret"         "${X_CLIENT_SECRET:-}"
push_secret "postiz-linkedin-client-id"      "${LINKEDIN_CLIENT_ID:-}"
push_secret "postiz-linkedin-client-secret"  "${LINKEDIN_CLIENT_SECRET:-}"
push_secret "postiz-tiktok-client-id"        "${TIKTOK_CLIENT_ID:-}"
push_secret "postiz-tiktok-client-secret"    "${TIKTOK_CLIENT_SECRET:-}"
push_secret "postiz-pinterest-client-id"     "${PINTEREST_CLIENT_ID:-}"
push_secret "postiz-pinterest-client-secret" "${PINTEREST_CLIENT_SECRET:-}"
push_secret "postiz-youtube-client-id"       "${YOUTUBE_CLIENT_ID:-}"
push_secret "postiz-youtube-client-secret"   "${YOUTUBE_CLIENT_SECRET:-}"

# ── Deploy Cloud Run service ───────────────────────────────────────────────────
INSTANCE_CONNECTION="${GCLOUD_PROJECT}:${GCLOUD_REGION}:postiz-pg"

echo "==> Deploying Cloud Run service ${CLOUD_RUN_SERVICE} ..."
run gcloud run deploy "${CLOUD_RUN_SERVICE}" \
  --image="${CLOUD_RUN_IMAGE}" \
  --region="${GCLOUD_REGION}" \
  --project="${GCLOUD_PROJECT}" \
  --service-account="${SA_EMAIL}" \
  --add-cloudsql-instances="${INSTANCE_CONNECTION}" \
  --allow-unauthenticated \
  --port=3000 \
  --memory=1Gi \
  --cpu=1 \
  --min-instances=0 \
  --max-instances=2 \
  --set-secrets=\
DATABASE_URL=postiz-database-url:latest,\
REDIS_URL=postiz-redis-url:latest,\
JWT_SECRET=postiz-jwt-secret:latest,\
BACKEND_INTERNAL_URL=postiz-backend-url:latest,\
NEXT_PUBLIC_BACKEND_URL=postiz-backend-url:latest,\
FRONTEND_URL=postiz-backend-url:latest,\
INSTAGRAM_CLIENT_ID=postiz-instagram-client-id:latest,\
INSTAGRAM_CLIENT_SECRET=postiz-instagram-client-secret:latest,\
FACEBOOK_CLIENT_ID=postiz-facebook-client-id:latest,\
FACEBOOK_CLIENT_SECRET=postiz-facebook-client-secret:latest,\
X_CLIENT_ID=postiz-x-client-id:latest,\
X_CLIENT_SECRET=postiz-x-client-secret:latest,\
LINKEDIN_CLIENT_ID=postiz-linkedin-client-id:latest,\
LINKEDIN_CLIENT_SECRET=postiz-linkedin-client-secret:latest,\
TIKTOK_CLIENT_ID=postiz-tiktok-client-id:latest,\
TIKTOK_CLIENT_SECRET=postiz-tiktok-client-secret:latest,\
PINTEREST_CLIENT_ID=postiz-pinterest-client-id:latest,\
PINTEREST_CLIENT_SECRET=postiz-pinterest-client-secret:latest,\
YOUTUBE_CLIENT_ID=postiz-youtube-client-id:latest,\
YOUTUBE_CLIENT_SECRET=postiz-youtube-client-secret:latest \
  --quiet

# ── Print the service URL ──────────────────────────────────────────────────────
if ! "${DRY_RUN}"; then
  SERVICE_URL="$(gcloud run services describe "${CLOUD_RUN_SERVICE}" \
    --region="${GCLOUD_REGION}" \
    --project="${GCLOUD_PROJECT}" \
    --format='value(status.url)')"
  echo ""
  echo "==> Postiz deployed at: ${SERVICE_URL}"
  echo ""
  echo "Next steps:"
  echo "  1. Update BACKEND_INTERNAL_URL in .env.postiz to ${SERVICE_URL}"
  echo "  2. Re-run this script to push the corrected backend URL secret."
  echo "  3. Open ${SERVICE_URL} in a browser and run database migrations:"
  echo "       gcloud run jobs create postiz-migrate \\"
  echo "         --image=${CLOUD_RUN_IMAGE} \\"
  echo "         --region=${GCLOUD_REGION} \\"
  echo "         --command=npx,prisma,migrate,deploy \\"
  echo "         --set-secrets=DATABASE_URL=postiz-database-url:latest"
  echo "  4. Visit ${SERVICE_URL} → Settings → Integrations and connect each platform."
  echo "  5. Copy the Postiz API key from Settings → API Keys."
  echo "  6. Wire secrets to Cloudflare Workers staging:"
  echo "       wrangler secret put POSTIZ_API_URL --env staging"
  echo "       wrangler secret put POSTIZ_API_KEY --env staging"
  echo "       # then the per-platform integration IDs shown in Postiz UI"
fi
