/**
 * Generate the event-recap video template previews: the full template × format
 * fan-out for each fixture event, written as standalone HyperFrames HTML
 * documents plus a manifest and a browsable index.
 *
 *   npx tsx scripts/event-recap-video-previews.ts
 *
 * Output (repo-relative, committed as review evidence):
 *   docs/explorations/motion-graphics/template-previews/<eventId>/<templateId>--<format>.html
 *   docs/explorations/motion-graphics/template-previews/manifest.json
 *   docs/explorations/motion-graphics/template-previews/index.html
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  planRecapVariants,
  renderRecapVideo,
  type RecapFormat,
  type RecapVideoData,
} from '../lib/video/event-recap';
import aie2026 from '../lib/video/event-recap/fixtures/aie-2026.recap';
import devsummit2026 from '../lib/video/event-recap/fixtures/devsummit-2026.recap';

const OUT_DIR = join(
  __dirname,
  '..',
  'docs',
  'explorations',
  'motion-graphics',
  'template-previews',
);
const FORMATS: RecapFormat[] = ['vertical', 'square', 'landscape'];
const EVENTS: RecapVideoData[] = [aie2026, devsummit2026];

interface ManifestEntry {
  eventId: string;
  templateId: string;
  format: RecapFormat;
  width: number;
  height: number;
  durationSeconds: number;
  status: 'renderable' | 'skipped';
  reason?: string;
  file?: string;
}

const manifest: ManifestEntry[] = [];

for (const data of EVENTS) {
  const eventDir = join(OUT_DIR, data.event.eventId);
  mkdirSync(eventDir, { recursive: true });
  for (const entry of planRecapVariants(data, FORMATS)) {
    const base: ManifestEntry = {
      eventId: data.event.eventId,
      templateId: entry.templateId,
      format: entry.format,
      width: entry.width,
      height: entry.height,
      durationSeconds: entry.durationSeconds,
      status: entry.status,
    };
    if (entry.status === 'skipped') {
      manifest.push({ ...base, reason: entry.reason });
      continue;
    }
    const file = `${data.event.eventId}/${entry.templateId}--${entry.format}.html`;
    writeFileSync(
      join(OUT_DIR, file),
      renderRecapVideo(entry.templateId, data, { format: entry.format }),
    );
    manifest.push({ ...base, file });
  }
}

writeFileSync(join(OUT_DIR, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

const rows = manifest
  .map((m) => {
    const cell = m.file
      ? `<a href="${m.file}">${m.templateId}--${m.format}.html</a>`
      : `<em>skipped — ${m.reason}</em>`;
    return `      <tr><td>${m.eventId}</td><td>${m.templateId}</td><td>${m.format}</td><td>${m.width}×${m.height}</td><td>${m.durationSeconds}s</td><td>${cell}</td></tr>`;
  })
  .join('\n');

writeFileSync(
  join(OUT_DIR, 'index.html'),
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>event-recap template previews</title>
    <style>
      body { background: #f4ede0; color: #1a1a1a; font-family: ui-monospace, monospace; padding: 40px; }
      table { border-collapse: collapse; }
      td, th { border: 1px solid rgba(26,26,26,0.2); padding: 6px 14px; text-align: left; }
      a { color: #c8413a; }
    </style>
  </head>
  <body>
    <h1>event-recap template previews</h1>
    <p>Generated by <code>npx tsx scripts/event-recap-video-previews.ts</code>. Each link is a standalone HyperFrames document; open it and run <code>window.__timelines.main.play()</code> in the console to watch the composition.</p>
    <table>
      <tr><th>event</th><th>template</th><th>format</th><th>canvas</th><th>duration</th><th>preview</th></tr>
${rows}
    </table>
  </body>
</html>
`,
);

const rendered = manifest.filter((m) => m.status === 'renderable').length;
const skipped = manifest.length - rendered;
console.log(
  `wrote ${rendered} previews (${skipped} skipped) + manifest.json + index.html under ${OUT_DIR}`,
);
