interface Env {
  AETHER_ASSETS: {
    get(key: string): Promise<{
      body: ReadableStream;
      httpMetadata?: { contentType?: string };
      text?: () => Promise<string>;
    } | null>;
  };
}

const DATA_KEY = 'event-recap-ai-engineer-singapore/public.json';
const MEDIA_PREFIX = 'event-recap-ai-engineer-singapore/media/';
const DATA_VERSION = 'story-aware-11-root701-synthesis-1779287898';

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/vibes/aie2026/data') {
      const object = await env.AETHER_ASSETS.get(DATA_KEY);
      if (!object) return json({ ok: false, error: 'recap data not found' }, 404);
      return new Response(object.body, {
        headers: {
          'cache-control': 'public, max-age=120',
          'content-type': object.httpMetadata?.contentType ?? 'application/json; charset=utf-8',
        },
      });
    }

    if (url.pathname === '/vibes/aie2026/media') {
      const key = url.searchParams.get('path') ?? '';
      if (!key.startsWith(MEDIA_PREFIX)) return json({ ok: false, error: 'invalid media path' }, 400);
      const object = await env.AETHER_ASSETS.get(key);
      if (!object) return json({ ok: false, error: 'media not found' }, 404);
      return new Response(object.body, {
        headers: {
          'cache-control': 'public, max-age=86400',
          'content-type': object.httpMetadata?.contentType ?? contentType(key),
        },
      });
    }

    if (url.pathname === '/vibes/aie2026' || url.pathname === '/vibes/aie2026/') {
      return new Response(renderHtml(), {
        headers: {
          'cache-control': 'public, max-age=60',
          'content-type': 'text/html; charset=utf-8',
        },
      });
    }

    return new Response('Not found', { status: 404 });
  },
};

function json(value: unknown, status = 200): Response {
  return new Response(JSON.stringify(value), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' },
  });
}

function contentType(key: string): string {
  const lower = key.toLowerCase();
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg';
  if (lower.endsWith('.png')) return 'image/png';
  if (lower.endsWith('.webp')) return 'image/webp';
  if (lower.endsWith('.gif')) return 'image/gif';
  if (lower.endsWith('.mp4')) return 'video/mp4';
  if (lower.endsWith('.webm')) return 'video/webm';
  if (lower.endsWith('.mov')) return 'video/quicktime';
  return 'application/octet-stream';
}

function renderHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>AI Engineer Singapore vibes</title>
<style>
:root{color-scheme:light;--bg:#fbfaf7;--panel:#fffdfa;--ink:#24211f;--muted:#706960;--dim:#9b9186;--line:#e9e1d7;--accent:#de7340;--soft:#f4eee7}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
a{color:inherit;text-underline-offset:3px;text-decoration-thickness:.08em}button,a,summary{touch-action:manipulation}button:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.shell{display:grid;grid-template-columns:minmax(240px,320px) minmax(0,1fr);gap:22px;max-width:1680px;margin:0 auto;padding:28px}
.side{position:sticky;top:24px;max-height:calc(100dvh - 48px);overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable;border:1px solid var(--line);background:var(--panel);padding:22px}.eyebrow,.chip,.meta{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em}
.eyebrow{font-size:12px;color:var(--dim)}h1{font-family:Georgia,serif;font-size:clamp(32px,3vw,42px);line-height:1.04;margin:10px 0 16px;overflow-wrap:anywhere}h2{font-family:Georgia,serif;font-size:28px;line-height:1.14;margin:0}h3{font-family:Georgia,serif;font-size:22px;line-height:1.18;margin:0}
.meta{font-size:12px;color:var(--muted)}.method{margin-top:22px;border-top:1px solid var(--line);padding-top:16px}.method summary{cursor:pointer}.method-line{display:grid;gap:2px;margin:10px 0 0;color:var(--muted);font-size:13px;line-height:1.35}.method-line b{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em;color:#514b45}.method-facts{display:grid;gap:7px;margin-top:12px}.method-facts span{border:1px solid var(--line);background:#fff;padding:7px 9px;font:11px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.method details details{margin-top:10px}.method details details summary{font-size:11px}.method ul{max-height:180px;overflow:auto;margin:8px 0 0;padding-left:18px;color:var(--muted);font-size:12px}.method li{margin:4px 0}.method code{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;overflow-wrap:anywhere}
.main{min-width:0}.hero{border:1px solid var(--line);background:var(--panel);padding:24px}.lede{max-width:1040px;font-size:18px;color:#5b554e;margin:10px 0 0}.tags{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}
.chip{border:1px solid var(--line);border-radius:999px;background:#fff;padding:4px 10px;font-size:12px;color:#6f655c}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:22px}
.metric{border:1px solid var(--line);background:#fff;padding:14px}.metric b{display:block;font-family:Georgia,serif;font-size:34px;line-height:1}.metric span{display:block;margin-top:6px;color:var(--muted);font-size:13px}
.synthesis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:20px}.signal{border:1px solid var(--line);background:#fff;padding:14px;min-height:132px}.signal b{display:block;font-family:Georgia,serif;font-size:21px;line-height:1.15}.signal span{display:block;margin-top:8px;color:var(--muted);font-size:14px}
.coverage{display:flex;flex-wrap:wrap;align-items:stretch;gap:8px;margin-top:14px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:10px 0}.coverage-label{display:flex;align-items:center;padding:0 4px 0 0;font:11px ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--dim)}.coverage-item{min-width:124px;padding:9px 12px;border:1px solid var(--line);background:#fff;text-align:left;cursor:pointer}.coverage-item:hover,.coverage-item.active{background:#fff8f2}.coverage-item.active{border-color:var(--accent);box-shadow:inset 0 -2px 0 var(--accent)}.coverage-item.clear{min-width:0}.coverage-item b{display:block;font:14px ui-monospace,SFMono-Regular,Menlo,monospace;color:#514b45}.coverage-item span{display:block;margin-top:2px;font:11px ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--dim)}
.wall{display:grid;grid-template-columns:repeat(6,1fr);grid-auto-rows:122px;gap:8px;margin-top:20px}.tile{display:block;overflow:hidden;border:1px solid var(--line);background:var(--soft)}.tile.big{grid-column:span 2;grid-row:span 2}.tile img,.tile video{width:100%;height:100%;object-fit:cover;display:block;background:#111}
.tabs{display:flex;flex-wrap:wrap;gap:8px;margin:22px 0}.tabs button{border:1px solid var(--line);background:#fff;padding:8px 14px;font:14px ui-monospace,SFMono-Regular,Menlo,monospace;cursor:pointer}.tabs button.active{border-color:var(--accent);background:var(--accent);color:#fff}
.tools{display:flex;gap:10px;align-items:center;margin-bottom:14px}.tools input{width:min(520px,100%);border:1px solid var(--line);background:#fff;padding:10px 12px;font:14px ui-monospace,SFMono-Regular,Menlo,monospace}
.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{border:1px solid var(--line);background:var(--panel);padding:18px;min-width:0}.card.hot{border-color:var(--accent)}.card.selected{border-color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent)}.cluster-card{transition:border-color .16s ease,box-shadow .16s ease,background .16s ease}.cluster-card:hover{border-color:#d6a58d;box-shadow:0 8px 24px #6f4b3312}.card-actions{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-top:14px}
.atlas{border:1px solid var(--line);background:var(--panel);padding:18px;margin-bottom:14px}.atlas-head{display:flex;gap:12px;align-items:flex-start;justify-content:space-between}.atlas-head p{margin:4px 0 0;color:var(--muted);font-size:14px}.atlas-key{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.atlas-key span{border:1px solid var(--line);background:#fff;padding:5px 8px;font:11px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.atlas-map{position:relative;height:820px;min-height:560px;margin-top:14px;overflow:hidden;border:1px solid var(--line);background:#fff}.atlas-map:before{content:"";position:absolute;inset:0;z-index:0;background:linear-gradient(90deg,#f4eee7 1px,transparent 1px),linear-gradient(#f4eee7 1px,transparent 1px);background-size:54px 54px;opacity:.32}.atlas-lanes{position:absolute;inset:0;z-index:1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));pointer-events:none}.atlas-lane{padding:12px;border-right:1px solid #f1e8df;background:linear-gradient(180deg,#fffdfad6 0%,#fffdfa33 24%,transparent 100%)}.atlas-lane:last-child{border-right:0}.atlas-lane span{display:inline-block;max-width:18ch;font:11px/1.25 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.06em;color:#8d8176;background:#fffdfae8;padding:3px 5px}.atlas-links{position:absolute;inset:0;z-index:2;width:100%;height:100%;pointer-events:none}.atlas-node{position:absolute;z-index:3;min-height:0;transform:translate(-50%,-50%);border:1px solid var(--line);background:#fffdfa;padding:var(--node-pad,8px) calc(var(--node-pad,8px) + 2px);text-align:left;cursor:pointer;box-shadow:0 6px 14px #6f4b3318}.atlas-node:hover,.atlas-node.selected{z-index:5;border-color:var(--accent);background:#fff8f2}.atlas-node h4{margin:0;font-family:Georgia,serif;font-size:var(--node-title,14px);line-height:1.08}.atlas-node .meta{display:block;margin-top:5px;font-size:11px}.atlas-dot{display:inline-block;width:8px;height:8px;border-radius:999px;background:var(--accent);margin-right:6px}.atlas-method{margin-top:8px}.atlas-method summary{display:inline-block;cursor:pointer;border:1px solid var(--line);background:#fff;padding:6px 9px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.atlas-method p{margin:8px 0 0;font-size:13px;color:var(--muted);max-width:86ch}
.mix,.snips,.info{margin-top:12px}.snip{font:13px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);overflow-wrap:anywhere}.post{display:grid;gap:10px;border-top:1px solid var(--line);padding:18px 0;min-width:0}.post:first-child{border-top:0}.post-content{display:block;min-width:0}.post-text{font-size:15px;max-width:112ch;min-width:0;overflow-wrap:anywhere}.post-media{display:flex;gap:6px;overflow:auto}.post-content .post-media{display:grid;grid-template-columns:repeat(auto-fill,minmax(142px,172px));gap:6px;justify-content:start;overflow:visible;min-width:0;margin-top:12px}.post-media a,.cluster-media a,.tile{position:relative;display:block;cursor:pointer}.post-content .post-media a{overflow:hidden;min-width:0}.post-media a:hover img,.post-media a:hover video,.cluster-media a:hover img,.cluster-media a:hover video,.tile:hover img,.tile:hover video{filter:saturate(1.08) contrast(1.03)}.post-media img,.post-media video{width:150px;height:92px;object-fit:cover;border:1px solid var(--line);background:#111}.post-content .post-media img,.post-content .post-media video{width:100%;height:96px}
.score{position:relative;display:inline-block}.score summary{list-style:none;cursor:help;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);background:#fff3ec;border:1px solid #efd2c0;border-radius:4px;padding:2px 6px}.score summary::-webkit-details-marker{display:none}.score div{position:absolute;z-index:20;left:0;top:calc(100% + 4px);width:300px;border:1px solid var(--line);background:#fff;padding:10px;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);box-shadow:0 10px 24px #0002}
.row{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.platform{color:#5479a8}.source{color:var(--dim)}details.raw{margin-top:8px}.raw summary{cursor:pointer;color:var(--dim);font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.raw dl{display:grid;grid-template-columns:120px minmax(0,1fr);gap:4px 10px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}.raw dd{margin:0;overflow-wrap:anywhere}
.cluster-detail{border:1px solid var(--accent);background:#fff8f2;padding:18px;margin-bottom:14px}.cluster-detail h2{max-width:900px}.cluster-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center;justify-content:space-between}.ghost{border:1px solid var(--line);background:#fff;padding:7px 10px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;cursor:pointer}.cluster-media{display:grid;grid-template-columns:repeat(6,1fr);grid-auto-rows:104px;gap:6px;margin-top:8px}.cluster-media a{overflow:hidden;border:1px solid var(--line);background:var(--soft)}.cluster-media img,.cluster-media video{width:100%;height:100%;object-fit:cover;display:block;background:#111}.cluster-posts{margin-top:8px;border-top:1px solid var(--line)}.cluster-posts-head{display:flex;flex-wrap:wrap;gap:10px;align-items:center;justify-content:space-between;margin-top:16px;padding-top:12px;border-top:1px solid var(--line)}.media-note{margin:12px 0 0}.open-cluster{border:1px solid var(--ink);background:var(--ink);color:#fff;padding:9px 13px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.04em;cursor:pointer}.open-cluster:after{content:" ->"}.open-cluster:hover,.open-cluster:focus-visible{border-color:var(--accent);background:var(--accent)}
.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(148px,1fr));gap:8px}.media-grid a{height:128px;overflow:hidden;border:1px solid var(--line);background:var(--soft)}.media-grid img,.media-grid video{width:100%;height:100%;object-fit:cover;display:block}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:12px}.pager button{border:1px solid var(--line);background:#fff;padding:7px 10px;cursor:pointer}.empty{color:var(--muted);padding:24px;border:1px solid var(--line);background:#fff}
@media(max-width:1100px){.post-content .post-media{grid-template-columns:repeat(auto-fill,minmax(126px,1fr))}}
@media(max-width:900px){.shell{display:block;padding:14px}.side{position:static;max-height:none;margin-bottom:14px}h1{font-size:34px;overflow-wrap:normal}.metrics,.synthesis{grid-template-columns:repeat(2,1fr)}.coverage-item{flex:1 1 140px}.grid{grid-template-columns:1fr}.wall{grid-template-columns:repeat(3,1fr);grid-auto-rows:100px}.atlas-map{height:560px}.atlas-node{width:150px!important}.cluster-media{grid-template-columns:repeat(3,1fr);grid-auto-rows:92px}}
@media(max-width:640px){.synthesis{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="shell">
  <aside class="side">
    <p class="eyebrow">event</p>
    <h1>AI Engineer Singapore</h1>
    <p class="meta" id="dateRange">loading...</p>
    <div class="method">
      <details>
        <summary class="meta">method</summary>
        <p class="method-line"><b>Sample</b><span>Seed terms, source links, and discovered public refs.</span></p>
        <p class="method-line"><b>Limit</b><span>Evidence corpus, not a representative survey.</span></p>
        <p class="method-line"><b>Reach</b><span>X/YouTube views; LinkedIn public engagement.</span></p>
        <div id="methodDetails"></div>
      </details>
    </div>
  </aside>
  <main class="main">
    <section class="hero">
      <p class="eyebrow">synthesis</p>
      <h2>What travelled was evidence, not hype.</h2>
      <p class="lede" id="lede">Loading recap...</p>
      <div class="synthesis" id="synthesis"></div>
      <div class="metrics" id="metrics"></div>
      <div class="wall" id="wall"></div>
      <div class="pager"><span class="meta" id="wallCount"></span><span><button id="prevMedia">prev</button> <button id="nextMedia">next</button></span></div>
    </section>
    <nav class="tabs" id="tabs"></nav>
    <div class="coverage" id="sourceMix" aria-label="source filters"></div>
    <div class="tools"><input id="search" placeholder="search refs" /><span class="meta" id="visibleCount"></span></div>
    <section id="content"></section>
  </main>
</div>
<script>
const state={data:null,tab:'clusters',mediaPage:0,query:'',selectedTheme:null,coverageFilters:[],mediaTimer:null,mediaAutoPausedUntil:0};
const tabs=['clusters','refs','timeline','voices','media'];
const AUTO_MEDIA_MS=5200;
const MANUAL_MEDIA_PAUSE_MS=16000;
const $=(id)=>document.getElementById(id);
const fmt=(n)=>n==null?'0':Intl.NumberFormat('en',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n);
const date=(v)=>v?new Date(v).toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'}):'date pending';
const isImageUrl=(v)=>/\\.(jpe?g|png|webp|avif|gif)(\\?|$)/i.test(String(v||''));
const isVideoUrl=(v)=>/\\.(mp4|webm|mov|m4v)(\\?|$)/i.test(String(v||''));
const localMediaUrl=(m)=>m.path?'/vibes/aie2026/media?path='+encodeURIComponent(m.path):'';
const localImageUrl=(m)=>m.path&&isImageUrl(m.path)?localMediaUrl(m):'';
const remoteImageUrl=(m)=>isImageUrl(m.previewUrl)?m.previewUrl:isImageUrl(m.url)?m.url:'';
const imageUrl=(m)=>localImageUrl(m)||remoteImageUrl(m);
const videoUrl=(m)=>m.path&&isVideoUrl(m.path)?localMediaUrl(m):isVideoUrl(m.url)?m.url:'';
const isVideoMedia=(m)=>Boolean(videoUrl(m))&&(/^video\\//i.test(String(m.contentType||''))||String(m.type||'').toLowerCase()==='video'||isVideoUrl(m.path)||isVideoUrl(m.url));
const mediaUrl=(m)=>isVideoMedia(m)?videoUrl(m):imageUrl(m);
const isImageMedia=(m)=>Boolean(imageUrl(m));
const isRenderableMedia=(m)=>Boolean(mediaUrl(m));
const mediaKey=(m)=>m.visualHash||(m.path&&isImageUrl(m.path)?m.hash:undefined)||mediaUrl(m)||m.hash||m.path||m.url;
function mediaElement(m){const src=imageUrl(m);if(src){const fallback=remoteImageUrl(m);const onerror=localImageUrl(m)&&fallback&&fallback!==src?' onerror="this.onerror=null;this.src=\\''+escapeHtml(fallback)+'\\'"':' onerror="const p=this.closest(\\'a\\');if(p)p.remove()"';return'<img src="'+escapeHtml(src)+'" loading="lazy" alt="'+(isVideoMedia(m)?'video preview':'')+'"'+onerror+'>'}const video=videoUrl(m);return video?'<video src="'+escapeHtml(video)+'" muted playsinline loop preload="metadata" onerror="const p=this.closest(\\'a\\');if(p)p.remove()"></video>':''}
const raw=(p)=> ((p.metrics||{}).likes||0)+((p.metrics||{}).reactions||0)+2*((p.metrics||{}).comments||0)+2*((p.metrics||{}).reposts||0)+2*((p.metrics||{}).replies||0)+((((p.metrics||{}).views??(p.metrics||{}).impressions)??0)/200);
const score=(v,kind='eng')=>{const voice=kind==='voice';const help=voice?'Voice score highlights people with repeated high-signal refs and public engagement.':'Engagement score compares this ref with other refs on the same platform. 0 is typical; higher is above-platform average. Signals include public reactions, comments, reposts, and views where the platform exposes them.';return '<details class="score" title="'+help+'"><summary>'+kind+' '+Number(v||0).toFixed(2)+' ?</summary><div>'+help+(voice?'':'<br><br>LinkedIn impressions are not exposed here, so LinkedIn uses public reactions/comments/reposts only.')+'</div></details>'};
const publicSignal=(value)=>'<details class="score" title="Weighted public signal"><summary>'+fmt(value)+' public signal ?</summary><div>Weighted public engagement across this voice: likes/reactions + 2x comments/reposts/replies + views/200 where views are exposed. LinkedIn has no public views here.</div></details>';
const postTime=(p)=>Date.parse(p.postedAt||'')||Number(p.capturedAt||0)||Number(p.updatedAt||0)||0;
const postDateLabel=(p)=>p.postedAt?date(p.postedAt):p.capturedAt?'captured '+date(p.capturedAt):p.updatedAt?'updated '+date(p.updatedAt):'undated';
const handleDisplay=(handle,platform)=>{const h=String(handle||'').replace(/^@/,'').trim();if(!h)return'profile';if(platform==='x')return'@'+h;const parts=h.split(/[-_.]+/).filter(Boolean).filter((p,i,a)=>!(i===a.length-1&&(/\\d/.test(p)||/^[a-f0-9]{6,}$/i.test(p))));if(parts.length<2)return h;return parts.map(p=>{const l=p.toLowerCase();return /^(ai|api|llm|ml|sg|vc)$/.test(l)?l.toUpperCase():l[0].toUpperCase()+l.slice(1)}).join(' ')};
const cleanVoiceName=(name)=>{let n=extractLinkedInTitleName(name)||decodeText(name).replace(/\\s+/g,' ').trim().replace(/\\s+(?:is\\s+)?at\\s+(?:the\\s+)?ai\\s+engineer\\s+singapore.*$/i,'').replace(/\\s+(?:(?:is|was)\\s+)?at\\s+(?:the\\s+)?(?:ai\\s+eng\\s+sg|ai\\s+engineer\\s+sg|ai\\s+engineer\\s+summit|aie\\s+sg).*$/i,'').replace(/\\s+@\\s+ai\\s+engineer\\s+singapore.*$/i,'').replace(/\\s+@\\s*(?:ai\\s*(?:eng|engineer)\\s*(?:singapore|sg)|aie\\s*sg|aie)\\b.*$/i,'').replace(/\\s*[-–—]\\s*.*\\b(?:ai\\s+builder\\s+@\\s+aie|aie\\s+sg|ai\\s+eng(?:ineer)?\\s+singapore)\\b.*$/i,'').replace(/\\s*[-–—]\\s*ai\\s+builder\\s*$/i,'').replace(/\\s*\\([^)]*\\b(?:aie\\s+sg|ai\\s+engineer)\\b[^)]*\\)\\s*$/i,'').replace(/\\s+at\\s+aie\\s+singapore.*$/i,'').trim();if(/^[a-z]+(?:\\s+[a-z]+)*$/.test(n))n=n.split(/\\s+/).map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');if(!n||n.includes('#')||n.includes('|')||/^\\{.*\\btitle\\b/i.test(n)||/["']?\\btitle["']?\\s*:/i.test(n)||/\\bposted on the topic\\b/i.test(n)||/&(?:quot|#39|amp);/i.test(n)||/^\\d+(\\.\\d+)?\\s+(comments?|likes?|reactions?)$/i.test(n)||/\\s+·\\s+(luma|events calendar)$/i.test(n)||/^ai engineer singapore\\b/i.test(n)||/\\b(workshop|hackathon|meetup|conference|event|happy hour)\\b.*\\bai engineer singapore\\b/i.test(n)||/\\bcome and join us\\b.*\\bai engineer\\b/i.test(n)||/\\bai engineer day singapore\\b/i.test(n)||/^(i'?ll|i am|here at|hehe i am)\\b.*\\b(ai engineer|aie)\\b/i.test(n)||n.length>=96)return'';return n};
const voiceName=(v)=>cleanVoiceName(v.name)||handleDisplay(v.handle,v.platform);
function platformCounts(ids){const mix={x:0,linkedin:0,youtube:0};for(const id of ids||[]){const p=state.data.postsById[id];if(p&&Object.prototype.hasOwnProperty.call(mix,p.platform))mix[p.platform]++}return mix}
function platformChips(mix){return ['x','linkedin','youtube'].map(p=>[p,mix[p]||0]).filter(([,n])=>n).map(([p,n])=>'<span class="chip">'+p+' '+n+'</span>').join('')}
function platformMix(ids){return platformChips(platformCounts(ids))}
function clusterCoverage(){const d=state.data;if(d.clusterCoverage)return d.clusterCoverage;const ids=new Set(d.posts.map(p=>p.postId));const clustered=new Set();let root=0;let attached=0;for(const t of d.themes||[]){for(const id of t.postIds||[])if(ids.has(id))clustered.add(id);root+=new Set((t.rootPostIds||t.postIds||[]).filter(id=>ids.has(id))).size;attached+=new Set((t.attachedPostIds||[]).filter(id=>ids.has(id))).size}return{totalRefs:d.posts.length,clusteredRefs:clustered.size,rootRefs:root||clustered.size,attachedRefs:attached,unclusteredRefs:Math.max(0,d.posts.length-clustered.size)}}
function decodeText(s){const el=document.createElement('textarea');el.innerHTML=String(s||'');return el.value}
function extractLinkedInTitleName(s){const decoded=decodeText(s).replace(/\s+/g,' ').trim();for(const segment of decoded.split('|')){const match=segment.trim().match(/^(.+?)\s+posted on the topic\b/i);if(match&&match[1]&&!/[{}#|]/.test(match[1]))return match[1].trim()}return''}
function postLine(p){const media=(p.media||[]).filter(isRenderableMedia);const context=(p.tags||[]).includes('context:event')?'<span class="chip">context</span>':'';const story=p.storyType?'<span class="chip">'+escapeHtml(String(p.storyType).replace(/_/g,' '))+'</span>':'';const mentions=(p.storyMentions||[]).map(m=>m.label+(m.role==='secondary'?' (secondary)':'')).join(', ');return '<article class="post"><div class="row"><span class="chip platform">'+p.platform+'</span>'+context+story+'<span class="meta">'+(p.authorHandle||p.authorName||'unknown')+'</span><span class="meta">'+postDateLabel(p)+'</span>'+(media.length?'<span class="chip">'+media.length+' media</span>':'')+score(p.reachScore)+'<a class="meta" href="'+p.url+'" target="_blank" rel="noreferrer">open original</a></div><div class="post-content '+(media.length?'has-media':'')+'"><div class="post-text">'+escapeHtml(decodeText(p.text))+'</div>'+mediaStrip(p)+'</div><details class="raw"><summary>complete post info</summary><dl><dt>url</dt><dd><a href="'+p.url+'" target="_blank">'+p.url+'</a></dd><dt>raw engagement</dt><dd>'+raw(p).toFixed(2)+'</dd><dt>story</dt><dd>'+escapeHtml(mentions||p.primaryStoryId||'unassigned')+'</dd><dt>media</dt><dd>'+media.length+' local assets'+(media.length?'<ol>'+media.map(m=>'<li><a href="'+mediaUrl(m)+'" target="_blank" rel="noreferrer">'+escapeHtml(m.path||m.url)+'</a></li>').join('')+'</ol>':'')+'</dd><dt>metrics</dt><dd>'+escapeHtml(JSON.stringify(p.metrics||{}))+'</dd><dt>tags</dt><dd>'+escapeHtml((p.tags||[]).join(', '))+'</dd></dl></details></article>'}
function mediaStrip(p){const imgs=(p.media||[]).filter(isRenderableMedia);return imgs.length?'<div class="post-media">'+imgs.map((m,i)=>'<a href="'+mediaUrl(m)+'" target="_blank" rel="noreferrer" title="open media '+(i+1)+' of '+imgs.length+'" data-action="open media">'+mediaElement(m)+'</a>').join('')+'</div>':''}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function filterSet(){return new Set(state.coverageFilters||[])}
function postMatchesCoverage(p){const filters=filterSet();if(!filters.size)return true;return [...filters].some(filter=>filter==='videos'?(p.platform==='youtube'&&p.tags?.includes('youtube-video')):p.platform===filter)}
function mediaMatchesCoverage(m){const filters=filterSet();if(!filters.size)return true;const post=state.data.postsById[m.postId]||{};return [...filters].some(filter=>filter==='videos'?(post.platform==='youtube'&&post.tags?.includes('youtube-video')):m.postPlatform===filter)}
function voiceMatchesCoverage(v){const filters=filterSet();if(!filters.size)return true;return [...filters].some(filter=>filter==='videos'?v.platform==='youtube':v.platform===filter)}
function filteredMedia(){return (state.data?.media||[]).filter(mediaMatchesCoverage)}
function filteredPosts(){const q=state.query.toLowerCase();return state.data.posts.filter(p=>postMatchesCoverage(p)&&(!q||[p.text,p.authorName,p.authorHandle,p.platform].join(' ').toLowerCase().includes(q)))}
function coverageName(){const names={x:'X',linkedin:'LinkedIn',youtube:'YouTube',videos:'video'};return (state.coverageFilters||[]).map(filter=>names[filter]).filter(Boolean).join(' + ')}
function toggleCoverage(action){if(action==='clear'){state.coverageFilters=[]}else{const next=new Set(state.coverageFilters||[]);next.has(action)?next.delete(action):next.add(action);state.coverageFilters=[...next]}state.selectedTheme=null;state.mediaPage=0;render()}
const LOCAL_STOPWORDS=new Set('about after again also and are because been being but can cannot could did does down each event from have here how into its just like may more much need not now off only our out over same she should singapore summit than that the their them then there these they this those through too use was were what when where which while with you your ai aie engineer engineers conference'.split(' '));
function clusterTerms(text){return String(text||'').toLowerCase().replace(/https?:\\/\\/\\S+/g,' ').replace(/[^a-z0-9]+/g,' ').split(/\\s+/).map(w=>w.trim()).filter(w=>w.length>=3&&!LOCAL_STOPWORDS.has(w))}
function normalizeMap(vector){let norm=0;for(const value of vector.values())norm+=value*value;norm=Math.sqrt(norm);if(!norm)return vector;for(const entry of vector)vector.set(entry[0],entry[1]/norm);return vector}
function vectorSimilarity(left,right){let score=0;const small=left.size<=right.size?left:right;const large=left.size<=right.size?right:left;for(const entry of small)score+=entry[1]*(large.get(entry[0])||0);return clamp(score,0,1)}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
function uniqList(...lists){return Array.from(new Set(lists.flat().filter(Boolean)))}
function postDateKey(p){return [p.platform,(p.authorHandle||p.authorName||'').toLowerCase(),decodeText(p.text).toLowerCase().replace(/\\s+/g,' ').slice(0,420)].join('|')}
function hydratePostDates(posts){const dates=new Map();for(const p of posts){if(p.postedAt)dates.set(postDateKey(p),p.postedAt)}for(const p of posts){if(!p.postedAt&&dates.has(postDateKey(p)))p.postedAt=dates.get(postDateKey(p))}return posts}
const DISPLAY_THEME_OVERRIDES={
'story-vivian-builder-keynote':{label:'Vivian Balakrishnan\\'s builder keynote',summary:'The largest story is the foreign minister showing his own AI workflow: Raspberry Pi, NanoClaw, WhatsApp, second-brain use cases, and the line about not governing technology you have only been briefed on.'},
'atlas-04-kaspar-hidayat-ivan-leo-love':{label:'Student tickets and organizer love',summary:'Student scholarship posts, organizer thank-yous, and warm attendee recaps point to the community layer around the conference. Some general recaps sit here because they name the same organizers and student-ticket story.'},
'atlas-05-agrimsingh-off-incredible':{label:'Stage moments and organizer shoutouts',summary:'A broad stage-and-recap cluster: speaker milestones, livestream reactions, memorable room moments, and repeated credit to Agrim Singh, Sherry Jiang, 65labs, and the organizing crew.'},
'atlas-07-codex-gabriel-chua-chua':{label:'OpenAI Codex booth and workshops',summary:'Gabriel Chua and related posts document OpenAI\\'s footprint: Codex booth demos, Codex technical workshops, Codex for Everyone, FDE lunch chat, and day-by-day OpenAI recaps.'},
'atlas-08-codex-hack-design':{label:'Codex hack night and Cursor design',summary:'A tools-and-builds cluster spanning the Codex realtime hack night, Cursor design speaker reveal, robotics/software talks, and official livestream posts that circulated around the same tool-builder audience.'},
'atlas-09-hackathon-code-same':{label:'Expo booths, hiring and hallway conversations',summary:'Expo-floor and hallway texture: Google DeepMind booth posts, Exa hiring, sponsor conversations, founder dinners, and attendee notes that the side conversations mattered as much as the stage.'},
'atlas-10-robot-robotics-kai-ming':{label:'Reachy rap battle and creative demos',summary:'Creative AI moments anchored by the Hugging Face/Pollen Robotics Reachy rap battle, Synthaesthetic Art, and recaps framing the weekend as Singapore\\'s builder scene recognizing itself.'},
'atlas-11-workflows-workshop-days':{label:'Agentic workflow workshops and Singapore takeaways',summary:'Workshop-heavy posts around LlamaIndex, x402/pay.sh, agentic workflows, and practical builder sessions, mixed with attendee reflections on what Singapore\\'s AI scene can be.'},
'atlas-12-openai-openai-google-google':{label:'Sponsor lineup and Day 1 livestream',summary:'Official Day 1 video and sponsor-announcement posts: OpenAI, Google DeepMind, Cursor, Vercel, Cloudflare, Stripe, Convex, Featherless, Daytona, MiroMind, and related launch-week context.'},
'atlas-13-meetup-computer-convex':{label:'Road to AIE meetups and hackathon runway',summary:'Pre-conference momentum from Road to AIE meetups, Convex boba, Daytona and AI Tinkerers gatherings, plus hackathon winner notes that show the build-up before the main conference.'},
'atlas-14-google-happy-hour-startup':{label:'Google happy hour and founder conversations',summary:'Google for Startups and Google DeepMind side programming: closed-door founder happy hour, startup conversations, and adjacent attendee posts about the sponsor/community surface.'},
'atlas-15-cursor-vercel-workshop':{label:'Friday workshop day',summary:'Friday workshop recaps across Stripe, AWS, Vercel, Convex, Arize, OpenAI/Codex, and sponsor sessions, plus posts arguing that serious AI building no longer has to center only on SF.'},
'atlas-16-software-factories-software-factories':{label:'Leadership track and software factories',summary:'Leadership-track and enterprise-building posts: software factories, deploying coding agents inside organizations, packed-house talks, and how AI changes product and engineering workflows.'},
'atlas-17-reality-talk-code':{label:'Design talks and Singapore reality check',summary:'A mixed talk-reaction cluster: MagicPath/design-system moments, evolutionary algorithms and tool demos, plus a contrarian X thread questioning whether Singapore is really becoming a global AI hub.'},
'atlas-18-understand-physics-research':{label:'Research talks and model systems',summary:'Research-track coverage around sovereign AI, world models, physical AI, MoE inference, and speaker recaps from teams like Sakana AI, Reka, Cerebras, and related builders.'},
'atlas-19-credits-adaption-labs-prizes':{label:'Build-week credits and small recaps',summary:'A mixed bridge cluster around the Road to AIE build-up: hackathon prize posts and API-credit offers sit next to workshop notes, talk-upload links, and short conference praise. It is build-week logistics and small receipts, not a standalone hackathon story.'},
'atlas-21-tencent-cloud-built-kept':{label:'AI Tinkerers and Tencent side event',summary:'Small side-event cluster around AI Tinkerers, GFTN, Tencent Cloud, and Built Different: Agent Edition, with a few broader attendee reflections that share the same side-event and builder-community language.'}
};
function displayTheme(t){return DISPLAY_THEME_OVERRIDES[t.themeId]?{...t,...DISPLAY_THEME_OVERRIDES[t.themeId]}:t}
function mergeDisplayThemes(themes){const mergeIds=new Set(['atlas-01-minister-balakrishnan-vivian-balakrishnan','atlas-03-built-tools-minister','atlas-06-minister-foreign-foreign-affairs']);const parts=themes.filter(t=>mergeIds.has(t.themeId));if(parts.length<2)return themes.map(displayTheme);const merged=displayTheme({...parts[0],themeId:'story-vivian-builder-keynote',postIds:uniqList(...parts.map(t=>t.postIds||[])),rootPostIds:uniqList(...parts.map(t=>t.rootPostIds||[])),attachedPostIds:uniqList(...parts.map(t=>t.attachedPostIds||[])),keywords:uniqList(...parts.map(t=>t.keywords||[])).slice(0,22),mergedThemeIds:parts.map(t=>t.themeId)});return themes.flatMap(t=>t.themeId===parts[0].themeId?[merged]:mergeIds.has(t.themeId)?[]:[displayTheme(t)])}
function buildClusterVectors(themes){const documents=themes.map(t=>clusterTerms([t.label,t.summary,(t.keywords||[]).join(' '),(t.keywords||[]).join(' '),(t.postIds||[]).slice(0,90).map(id=>{const p=state.data.postsById[id];return p?[(p.authorHandle||p.authorName||''),p.text,(p.tags||[]).join(' ')].join(' '):''}).join(' ')].join(' ')));const df=new Map();for(const terms of documents){for(const term of new Set(terms))df.set(term,(df.get(term)||0)+1)}return documents.map(terms=>{const counts=new Map();for(const term of terms)counts.set(term,(counts.get(term)||0)+1);const weighted=Array.from(counts.entries()).map(([term,count])=>[term,Math.log1p(count)*Math.log(1+documents.length/(1+(df.get(term)||1)))]).sort((a,b)=>b[1]-a[1]).slice(0,90);return normalizeMap(new Map(weighted))})}
const ATLAS_LANES=[{id:'program',label:'talks + research',x:.13},{id:'keynote',label:'keynote + stage signal',x:.38},{id:'tools',label:'hands-on tools + demos',x:.62},{id:'community',label:'community + sponsors',x:.86}];
function atlasLaneFor(t){const label=String(t.label||'').toLowerCase();const text=[t.label,t.summary,(t.keywords||[]).join(' ')].join(' ').toLowerCase();const key=/\\b(vivian|minister|balakrishnan|raspberry|nanoclaw|keynote|foreign affairs|second brain|stage moments?)\\b/;const program=/\\b(research|talks?|track|speaker|inference|world models?|leadership|program|sessions?)\\b/;const tools=/\\b(codex|cursor|hack|api|credit|agentic|workflow|workshops?|demo|reachy|rap|creative|openai|software factories)\\b/;const community=/\\b(students?|organizers?|organisers?|sponsors?|booths?|hiring|happy hour|meetups?|dinners?|afterglow|side events?|tinkerers|tencent|road to|livestream|shoutouts?)\\b/;if(key.test(label))return ATLAS_LANES[1];if(program.test(label))return ATLAS_LANES[0];if(tools.test(label))return ATLAS_LANES[2];if(community.test(label))return ATLAS_LANES[3];if(key.test(text))return ATLAS_LANES[1];if(program.test(text))return ATLAS_LANES[0];if(tools.test(text))return ATLAS_LANES[2];if(community.test(text))return ATLAS_LANES[3];return ATLAS_LANES[0]}
function buildAtlasLayout(themes){const vectors=buildClusterVectors(themes);const maxRefs=Math.max(1,...themes.map(t=>(t.postIds||[]).length));const nodes=themes.map((t,index)=>{const count=(t.postIds||[]).length;const weight=Math.sqrt(count/maxRefs);const width=142+Math.round(weight*132);const titleSize=(13.5+weight*5.5).toFixed(1);const pad=(7+weight*5).toFixed(1);const lines=Math.ceil(String(t.label||'').length/(16+weight*6));const height=48+Math.round(weight*18)+lines*(15+weight*4);const lane=atlasLaneFor(t);return{themeId:t.themeId,label:t.label,count,x:lane.x,y:.5,width,height,titleSize,pad,rx:(width/1160)/2,ry:(height/820)/2,mix:platformCounts(t.postIds||[]),index,lane}});const groups=new Map(ATLAS_LANES.map(l=>[l.id,[]]));for(const node of nodes)(groups.get(node.lane.id)||groups.get('program')).push(node);for(const lane of ATLAS_LANES){const list=(groups.get(lane.id)||[]).sort((a,b)=>b.count-a.count||a.index-b.index);const totalHeight=list.reduce((sum,node)=>sum+node.ry*2,0);const gap=Math.max(.024,Math.min(.085,(.82-totalHeight)/(list.length+1||1)));let cursor=.1+gap;list.forEach((node,i)=>{const nudge=list.length>2?((i%2?1:-1)*Math.min(.026,.006*list.length)):0;node.x=clamp(lane.x+nudge,node.rx+.025,1-node.rx-.025);node.y=clamp(cursor+node.ry,node.ry+.08,1-node.ry-.04);cursor+=node.ry*2+gap})}const pairs=[];for(let left=0;left<nodes.length;left++){for(let right=left+1;right<nodes.length;right++){pairs.push({source:nodes[left],target:nodes[right],similarity:vectorSimilarity(vectors[left],vectors[right])})}}const ranked=[...pairs].sort((a,b)=>b.similarity-a.similarity);const linkCounts=new Map();const links=[];const limit=Math.min(12,Math.max(5,themes.length-1));const addLink=(pair)=>{if(!pair||links.includes(pair))return;links.push(pair);linkCounts.set(pair.source.themeId,(linkCounts.get(pair.source.themeId)||0)+1);linkCounts.set(pair.target.themeId,(linkCounts.get(pair.target.themeId)||0)+1)};for(const pair of ranked){if(pair.similarity<.025)break;const s=pair.source.themeId;const t=pair.target.themeId;if((linkCounts.get(s)||0)>=2||(linkCounts.get(t)||0)>=2)continue;addLink(pair);if(links.length>=limit)break}for(const node of nodes){if(linkCounts.get(node.themeId))continue;addLink(ranked.find(pair=>pair.source===node||pair.target===node))}return{nodes,links}}
function renderAtlas(themes=state.data.themes||[]){const atlas=buildAtlasLayout(themes);const cov=clusterCoverage();const cq=state.data.clustering||{};const storyCount=themes.length;const rootRefs=cq.rootRefCount||cov.rootRefs;const refs=themes.reduce((sum,t)=>sum+((t.rootPostIds&&t.rootPostIds.length?t.rootPostIds:t.postIds)||[]).length,0)||cov.rootRefs;const lanes='<div class="atlas-lanes">'+ATLAS_LANES.map(l=>'<div class="atlas-lane"><span>'+escapeHtml(l.label)+'</span></div>').join('')+'</div>';const lines=atlas.links.map(link=>'<line x1="'+(link.source.x*100).toFixed(2)+'" y1="'+(link.source.y*100).toFixed(2)+'" x2="'+(link.target.x*100).toFixed(2)+'" y2="'+(link.target.y*100).toFixed(2)+'" stroke="#de7340" stroke-width="'+Math.max(.5,link.similarity*3.2).toFixed(2)+'" opacity="'+Math.min(.7,.14+link.similarity).toFixed(2)+'"/>').join('');const nodes=atlas.nodes.map(node=>'<button class="atlas-node '+(state.selectedTheme===node.themeId?'selected':'')+'" data-theme-node="'+escapeHtml(node.themeId)+'" title="'+escapeHtml(node.lane.label)+'" style="left:'+(node.x*100).toFixed(2)+'%;top:'+(node.y*100).toFixed(2)+'%;width:'+node.width+'px;--node-title:'+node.titleSize+'px;--node-pad:'+node.pad+'px"><h4><span class="atlas-dot"></span>'+escapeHtml(node.label)+'</h4><span class="meta">'+node.count+' refs</span></button>').join('');return '<section class="atlas" data-testid="cluster-distance-map"><div class="atlas-head"><div><p class="eyebrow">story map</p><h2>How the event stories sit together</h2><p>Columns are story families. Bigger cards have more refs. Lines mark the strongest shared language, authors, or cited refs.</p><div class="atlas-key"><span>columns = story family</span><span>size = ref count</span><span>lines = nearest shared signals</span></div></div><span class="chip">'+fmt(refs)+' refs mapped</span></div><div class="atlas-map">'+lanes+'<svg class="atlas-links" viewBox="0 0 100 100" preserveAspectRatio="none">'+lines+'</svg>'+nodes+'</div><details class="atlas-method"><summary>how this map works</summary><p>Grouped for reading, not literal coordinates. '+fmt(rootRefs)+' root refs are assigned to '+fmt(storyCount)+' whole-post stories. Broad recaps stay intact instead of being split; secondary story mentions are kept on the post.</p></details></section>'}
function bindClusterControls(){document.querySelectorAll('[data-theme-node],[data-cluster-open]').forEach(node=>{node.onclick=()=>{const id=node.getAttribute('data-theme-node')||node.getAttribute('data-cluster-open');state.selectedTheme=state.selectedTheme===id?null:id;renderContent()}});document.querySelectorAll('[data-clear-theme]').forEach(node=>{node.onclick=()=>{state.selectedTheme=null;renderContent()}})}
function themePosts(t){return (t.postIds||[]).map(id=>state.data.postsById[id]).filter(Boolean).sort((a,b)=>((b.reachScore||0)-(a.reachScore||0))||(postTime(b)-postTime(a)))}
function themeMedia(posts,limit){return posts.flatMap(p=>(p.media||[]).map(m=>({...m,postUrl:p.url}))).filter(isRenderableMedia).filter((m,i,arr)=>arr.findIndex(x=>mediaKey(x)===mediaKey(m))===i).slice(0,limit)}
function renderClusterDetail(t){if(!t)return'';const posts=themePosts(t);const q=state.query.toLowerCase();const shown=posts.filter(p=>!q||[p.text,p.authorName,p.authorHandle,p.platform].join(' ').toLowerCase().includes(q));const rootCount=(t.rootPostIds||t.postIds||[]).length;const attachedCount=(t.attachedPostIds||[]).length;const media=themeMedia(posts,18);return '<section class="cluster-detail" data-testid="cluster-detail"><div class="cluster-actions"><div><p class="eyebrow">cluster detail</p><h2>'+escapeHtml(t.label)+'</h2></div><button class="ghost" data-clear-theme>back to all clusters</button></div><div class="tags">'+platformMix(t.postIds||[])+'<span class="chip">'+posts.length+' refs</span><span class="chip">'+rootCount+' roots</span><span class="chip">'+attachedCount+' attached</span></div><p class="lede">'+escapeHtml(t.summary||'')+'</p>'+(media.length?'<p class="meta media-note">media opens source posts</p><div class="cluster-media">'+media.map(m=>'<a href="'+m.postUrl+'" target="_blank" rel="noreferrer" title="open source post" data-action="open post">'+mediaElement(m)+'</a>').join('')+'</div>':'')+'<div class="cluster-posts-head"><span class="meta">refs ordered by platform-normalized engagement score, then newer posts</span><span class="meta">'+shown.length+' shown</span></div><div class="cluster-posts">'+shown.map(postLine).join('')+'</div></section>'}
function renderClusterCard(t,i){const posts=themePosts(t);const rootCount=(t.rootPostIds||t.postIds||[]).length;const attachedCount=(t.attachedPostIds||[]).length;const media=themeMedia(posts,4);const selected=state.selectedTheme===t.themeId;return '<div class="card cluster-card '+(selected?'selected':i<2?'hot':'')+'" data-cluster-card="'+escapeHtml(t.themeId)+'"><div class="row"><h3>'+escapeHtml(t.label)+'</h3><span class="chip">'+posts.length+' refs</span><span class="chip">'+rootCount+' roots</span><span class="chip">'+attachedCount+' attached</span></div><div class="tags">'+platformMix(t.postIds||[])+'</div><p>'+escapeHtml(t.summary||'')+'</p>'+(media.length?'<div class="post-media">'+media.map(m=>'<a href="'+m.postUrl+'" target="_blank" rel="noreferrer" title="open source post" data-action="open post">'+mediaElement(m)+'</a>').join('')+'</div>':'')+'<div class="card-actions"><button class="open-cluster" data-cluster-open="'+escapeHtml(t.themeId)+'" aria-label="view refs for '+escapeHtml(t.label)+'">view refs</button>'+(media.length?'<span class="meta">media opens posts</span>':'')+'</div><div class="snips">'+posts.slice(0,3).map(p=>'<p class="snip">['+p.platform+'] '+escapeHtml((p.authorHandle||p.authorName||'unknown')+': '+decodeText(p.text).slice(0,180))+'...</p>').join('')+'</div></div>'}
function renderMethodology(){
const d=state.data;const cov=clusterCoverage();const m=d.methodology||{};const tiers=d.stats?.relevanceTiers||{};const q=m.querySet||d.querySet||{};const x=q.x||[];const exp=m.expansionQueries||[];const yt=m.youtubeSources||[];const sources=m.sourceLinks||[];const cq=d.clustering;const rawCount=cq?.rawClusterCount||cq?.elbowClusterCount||cq?.clusterCount;
const candidates=(cq?.candidateScores||[]).map(v=>'<li>'+v.clusterCount+' clusters: silhouette '+Number(v.silhouetteScore||0).toFixed(4)+' · inertia '+Number(v.inertia||0).toFixed(4)+' · elbow '+Number(v.elbowScore||0).toFixed(2)+'</li>').join('');
const relevanceRule='<details><summary class="meta">relevance rule</summary><ul><li>Refs need an AIE Singapore anchor plus substantive event evidence: program, speaker, sponsor, workshop, demo, media, logistics, or recap detail.</li><li>Context refs are replies, comments, photos, logistics, hallway notes, hashtag coordination, or source-media texture attached to a story.</li><li>Incidental attendance or adjacent AI-in-Singapore posts are excluded unless they add source media, useful logistics, speaker/program context, or concrete event texture.</li></ul></details>';
const clusterDetails=cq?'<details><summary class="meta">cluster details</summary><ul><li>'+fmt(cov.rootRefs)+' story roots + '+fmt(cov.attachedRefs)+' attached refs</li><li>Visible clusters use deterministic whole-post story assignment with precedence checks, not raw TF-IDF labels.</li><li>'+fmt(cq.storyAssignment?.broadRecapRefs||0)+' broad recaps kept intact; '+fmt(cq.storyAssignment?.multiMentionRefs||0)+' refs carry secondary story mentions.</li></ul></details><details><summary class="meta">technical diagnostics</summary><ul><li>TF-IDF is retained as a diagnostic baseline for overlap and map links, not as the public cluster label source.</li><li>diagnostic silhouette '+Number(cq.silhouetteScore||0).toFixed(4)+' · inertia '+Number(cq.inertia||0).toFixed(4)+'</li>'+candidates+'</ul></details>':'';
const sourceDetails=sources.length?'<details><summary class="meta">source links</summary><ul>'+sources.map(v=>'<li><a href="'+v.url+'" target="_blank" rel="noreferrer">'+escapeHtml(v.label||v.url)+'</a>'+(v.note?' <span class="meta">'+escapeHtml(v.note)+'</span>':'')+'</li>').join('')+'</ul></details>':'';
$('methodDetails').innerHTML='<div class="method-facts"><span>sources '+date(m.sourceDateRange?.start)+' - '+date(m.sourceDateRange?.end)+'</span><span>'+fmt(tiers.core||cov.rootRefs)+' core · '+fmt(tiers.context||0)+' context</span><span>'+fmt(cov.rootRefs)+' roots -> '+(d.themes||[]).length+' story clusters</span><span>whole posts retained; recaps can mention multiple stories</span></div>'+relevanceRule+clusterDetails+sourceDetails+'<details><summary class="meta">query seeds</summary><ul>'+x.concat(exp).slice(0,40).map(v=>'<li><code>'+escapeHtml(v)+'</code></li>').join('')+'</ul></details><details><summary class="meta">youtube sources</summary><ul>'+yt.map(v=>'<li><a href="'+v.url+'" target="_blank" rel="noreferrer">'+escapeHtml(v.title||v.url)+'</a> <span class="meta">'+fmt(v.views)+' views</span></li>').join('')+'</ul></details>'
}
function mediaPageCount(){return Math.max(1,Math.ceil(filteredMedia().length/15))}
function setMediaPage(next,manual=false){const pages=mediaPageCount();state.mediaPage=((next%pages)+pages)%pages;if(manual)state.mediaAutoPausedUntil=Date.now()+MANUAL_MEDIA_PAUSE_MS;renderWall()}
function startMediaCycle(){if(state.mediaTimer)clearInterval(state.mediaTimer);const reduce=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;if(!state.data||mediaPageCount()<2||reduce)return;state.mediaTimer=setInterval(()=>{const wall=$('wall');if(document.hidden||Date.now()<state.mediaAutoPausedUntil||(wall&&wall.matches(':hover')))return;setMediaPage(state.mediaPage+1)},AUTO_MEDIA_MS)}
function renderShell(){const d=state.data;const cov=clusterCoverage();$('dateRange').textContent=date(d.windowStart)+' to '+date(d.windowEnd)+' · refs through '+date(d.updatedAt);$('lede').textContent='The strongest refs were concrete: Vivian Balakrishnan showing his Raspberry Pi/NanoClaw workflow, packed workshops, booth and hallway photos, student-ticket gratitude, and side events that made Singapore feel like an active builder scene, not just a host city.';$('synthesis').innerHTML=[['What travelled','The line got attention; the details carried it: Raspberry Pi, NanoClaw, WhatsApp, second-brain workflows, and accountability from a minister using the stack.'],['What made it local','65labs, student tickets, sponsor booths, founder dinners, side meetups, and hallway photos made the recap feel locally owned.'],['Where the energy sat','Vivian dominated the corpus, but the surrounding signal is practical: workshops, Codex/OpenAI, sponsor rooms, research talks, and build-week side events.']].map(([title,body])=>'<div class="signal"><b>'+escapeHtml(title)+'</b><span>'+escapeHtml(body)+'</span></div>').join('');const c=d.stats.crossSurfaceObserved||{};$('metrics').innerHTML=[['primary refs',cov.rootRefs],['known views',c.knownViews],['public reactions',c.knownLikesAndLinkedInReactions],['media assets',d.mediaTotal]].map(([k,v])=>'<div class="metric"><b>'+fmt(v)+'</b><span>'+k+'</span></div>').join('');const by=d.stats.relevantByPlatform||{};const ytVideos=d.posts.filter(p=>p.platform==='youtube'&&p.tags?.includes('youtube-video')).length;const coverageItems=[['x','X refs',by.x||0],['linkedin','LinkedIn refs',by.linkedin||0],['youtube','YouTube refs',by.youtube||0],['videos','Videos',ytVideos]];const active=filterSet();$('sourceMix').innerHTML='<span class="coverage-label">filter</span>'+coverageItems.map(([action,label,value])=>'<button class="coverage-item '+(active.has(action)?'active':'')+'" data-coverage="'+action+'" aria-pressed="'+(active.has(action)?'true':'false')+'" title="toggle '+escapeHtml(label).toLowerCase()+'"><b>'+escapeHtml(value)+'</b><span>'+escapeHtml(label)+'</span></button>').join('')+(active.size?'<button class="coverage-item clear" data-coverage="clear" title="clear filters"><b>clear</b><span>filters</span></button>':'');$('sourceMix').querySelectorAll('[data-coverage]').forEach(b=>b.onclick=()=>toggleCoverage(b.dataset.coverage));$('tabs').innerHTML=tabs.map(t=>'<button data-tab="'+t+'" class="'+(state.tab===t?'active':'')+'">'+t+'</button>').join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.selectedTheme=null;render()});$('search').value=state.query;$('search').oninput=(e)=>{state.query=e.target.value;renderContent()};$('prevMedia').onclick=()=>setMediaPage(state.mediaPage-1,true);$('nextMedia').onclick=()=>setMediaPage(state.mediaPage+1,true);renderMethodology();renderWall();startMediaCycle()}
function renderWall(){const media=filteredMedia();const total=media.length;if(!total){$('wall').innerHTML='';$('wallCount').textContent='0 media';return}state.mediaPage=Math.min(state.mediaPage,mediaPageCount()-1);const page=media.slice(state.mediaPage*15,state.mediaPage*15+15);$('wall').innerHTML=page.map((m,i)=>'<a class="tile '+(i===0?'big':'')+'" href="'+m.postUrl+'" target="_blank" rel="noreferrer" title="open source post" data-action="open post">'+mediaElement(m)+'</a>').join('');$('wallCount').textContent=(state.mediaPage*15+1)+'-'+Math.min(total,state.mediaPage*15+15)+' / '+total+' · auto'}
function renderContent(){const d=state.data;const filterLabel=coverageName();const suffix=filterLabel?' · '+filterLabel:'';if(state.tab==='media'){const q=state.query.toLowerCase();const media=filteredMedia().filter(m=>!q||[m.postText,m.postAuthor,m.postPlatform,m.postUrl].join(' ').toLowerCase().includes(q));$('visibleCount').textContent=fmt(media.length)+' media assets'+suffix;$('content').innerHTML='<div class="card"><div class="media-grid">'+media.map((m,i)=>'<a class="tile" href="'+m.postUrl+'" target="_blank" rel="noreferrer" title="open source post" data-action="open post">'+mediaElement(m)+'</a>').join('')+'</div></div>';return}
if(state.tab==='refs'){const posts=filteredPosts();$('visibleCount').textContent=posts.length+' refs'+suffix;$('content').innerHTML='<div class="card">'+posts.map(postLine).join('')+'</div>';return}
if(state.tab==='voices'){const voices=d.voices.filter(v=>voiceMatchesCoverage(v)&&(!state.query||[voiceName(v),v.handle,v.platform].join(' ').toLowerCase().includes(state.query.toLowerCase())));$('visibleCount').textContent=voices.length+' voices'+suffix;$('content').innerHTML='<div class="grid">'+voices.map(v=>'<div class="card"><div class="row"><h3>'+escapeHtml(voiceName(v))+'</h3><span class="chip">'+v.platform+'</span>'+score(v.reachScore,'voice')+'</div><p class="meta">'+escapeHtml(v.handle||v.profileUrl||'profile')+' · '+v.postCount+' refs · '+publicSignal(v.totalEngagement)+'</p><p><a class="meta" href="'+(v.samplePostUrls?.[0]||v.profileUrl||'#')+'" target="_blank">open sample</a></p></div>').join('')+'</div>';return}
if(state.tab==='timeline'){const posts=filteredPosts().slice().sort((a,b)=>postTime(a)-postTime(b));$('visibleCount').textContent=posts.length+' dated refs'+suffix;$('content').innerHTML='<div class="card">'+posts.map(postLine).join('')+'</div>';return}
const makeThemeView=(t)=>{const postIds=(t.postIds||[]).filter(id=>{const p=d.postsById[id];return p&&postMatchesCoverage(p)});return{...t,postIds,rootPostIds:(t.rootPostIds||[]).filter(id=>postIds.includes(id)),attachedPostIds:(t.attachedPostIds||[]).filter(id=>postIds.includes(id))}};const themes=(d.themes||[]).map(makeThemeView).filter(t=>t.postIds.length);$('visibleCount').textContent=themes.length+' clusters · '+fmt(themes.reduce((sum,t)=>sum+(t.postIds||[]).length,0))+' refs'+suffix;const selected=themes.find(t=>t.themeId===state.selectedTheme);const sorted=[...themes].sort((a,b)=>state.selectedTheme?(a.themeId===state.selectedTheme?-1:b.themeId===state.selectedTheme?1:0):0);$('content').innerHTML=renderClusterDetail(selected)+renderAtlas(sorted)+'<div class="grid">'+sorted.map(renderClusterCard).join('')+'</div>';bindClusterControls()}
function render(){renderShell();renderContent()}
fetch('/vibes/aie2026/data?v=${DATA_VERSION}').then(r=>r.json()).then(d=>{d.posts=hydratePostDates(d.posts||[]);d.postsById=Object.fromEntries(d.posts.map(p=>[p.postId,p]));d.rawThemeCount=(d.themes||[]).length;d.themes=mergeDisplayThemes(d.themes||[]);d.media=[];const seen=new Set();let localMediaTotal=0;for(const p of d.posts){for(const m of p.media||[]){if(m.path)localMediaTotal++;const k=mediaKey(m);if(!k||seen.has(k)||!isRenderableMedia(m))continue;seen.add(k);d.media.push({...m,postUrl:p.url,postId:p.postId,postText:p.text,postAuthor:p.authorHandle||p.authorName,postPlatform:p.platform})}}d.media.sort((a,b)=>(b.bytes||0)-(a.bytes||0));d.mediaTotal=d.media.length;d.localMediaTotal=localMediaTotal;state.data=d;render()}).catch(err=>{const message=String(err&&err.message?err.message:err);$('content').innerHTML='<p class="empty">Could not load recap data'+(location.search.includes('debug=1')?': '+escapeHtml(message):'.')+'</p>';console.error(message)})
</script>
</body>
</html>`;
}
